//[File]            : wox_mcu_cfg_ls.h
//[Revision time]   : Fri Jul 30 12:19:25 2021
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2021 Mediatek Incorportion. All rights reserved.

#ifndef __WOX_MCU_CFG_LS_REGS_H__
#define __WOX_MCU_CFG_LS_REGS_H__


//****************************************************************************
//
//                     WOX_MCU_CFG_LS CR Definitions                     
//
//****************************************************************************

#define WOX_MCU_CFG_LS_BASE                                    0 /* 0x15194000 */

#define WOX_MCU_CFG_LS_HW_VER_ADDR                             (WOX_MCU_CFG_LS_BASE + 0x000) // 4000
#define WOX_MCU_CFG_LS_FW_VER_ADDR                             (WOX_MCU_CFG_LS_BASE + 0x004) // 4004
#define WOX_MCU_CFG_LS_CFG_DBG1_ADDR                           (WOX_MCU_CFG_LS_BASE + 0x00C) // 400C
#define WOX_MCU_CFG_LS_CFG_DBG2_ADDR                           (WOX_MCU_CFG_LS_BASE + 0x010) // 4010
#define WOX_MCU_CFG_LS_WOX_MCCR_ADDR                           (WOX_MCU_CFG_LS_BASE + 0x014) // 4014
#define WOX_MCU_CFG_LS_WOX_MCCR_SET_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x018) // 4018
#define WOX_MCU_CFG_LS_WOX_MCCR_CLR_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x01C) // 401C
#define WOX_MCU_CFG_LS_WOX_MCU_CFG_WO0_WO1_ADDR                (WOX_MCU_CFG_LS_BASE + 0x050) // 4050
#define WOX_MCU_CFG_LS_WOX_BOOT_ADDR_ADDR                      (WOX_MCU_CFG_LS_BASE + 0x060) // 4060
#define WOX_MCU_CFG_LS_WOX_CFG_CTL2_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x06C) // 406C
#define WOX_MCU_CFG_LS_WOX_GP_IRQ_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x080) // 4080
#define WOX_MCU_CFG_LS_FPGA_RSV_ADDR                           (WOX_MCU_CFG_LS_BASE + 0x100) // 4100
#define WOX_MCU_CFG_LS_RESERVE0_ADDR                           (WOX_MCU_CFG_LS_BASE + 0x150) // 4150
#define WOX_MCU_CFG_LS_WOX_COM_REG0_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x200) // 4200
#define WOX_MCU_CFG_LS_WOX_COM_REG1_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x204) // 4204
#define WOX_MCU_CFG_LS_WOX_COM_REG2_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x208) // 4208
#define WOX_MCU_CFG_LS_WOX_COM_REG3_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x20C) // 420C
#define WOX_MCU_CFG_LS_WOX_COM_REG4_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x210) // 4210
#define WOX_MCU_CFG_LS_WOX_COM_REG5_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x214) // 4214
#define WOX_MCU_CFG_LS_WOX_COM_REG6_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x218) // 4218
#define WOX_MCU_CFG_LS_WOX_COM_REG7_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x21C) // 421C
#define WOX_MCU_CFG_LS_WOX_COM_REG8_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x220) // 4220
#define WOX_MCU_CFG_LS_WOX_COM_REG9_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x224) // 4224
#define WOX_MCU_CFG_LS_WOX_COM_REG10_ADDR                      (WOX_MCU_CFG_LS_BASE + 0x228) // 4228
#define WOX_MCU_CFG_LS_WOX_COM_REG11_ADDR                      (WOX_MCU_CFG_LS_BASE + 0x22C) // 422C
#define WOX_MCU_CFG_LS_WOX_COM_REG12_ADDR                      (WOX_MCU_CFG_LS_BASE + 0x230) // 4230
#define WOX_MCU_CFG_LS_WOX_COM_REG13_ADDR                      (WOX_MCU_CFG_LS_BASE + 0x234) // 4234
#define WOX_MCU_CFG_LS_WOX_COM_REG14_ADDR                      (WOX_MCU_CFG_LS_BASE + 0x238) // 4238
#define WOX_MCU_CFG_LS_WOX_COM_REG15_ADDR                      (WOX_MCU_CFG_LS_BASE + 0x23C) // 423C
#define WOX_MCU_CFG_LS_WOX_SEMA0_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x320) // 4320
#define WOX_MCU_CFG_LS_WOX_SEMA1_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x324) // 4324
#define WOX_MCU_CFG_LS_WOX_SEMA2_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x328) // 4328
#define WOX_MCU_CFG_LS_WOX_SEMA3_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x32C) // 432C
#define WOX_MCU_CFG_LS_WOX_SEMA4_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x330) // 4330
#define WOX_MCU_CFG_LS_WOX_SEMA5_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x334) // 4334
#define WOX_MCU_CFG_LS_WOX_SEMA6_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x338) // 4338
#define WOX_MCU_CFG_LS_WOX_SEMA7_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x33C) // 433C
#define WOX_MCU_CFG_LS_WOX_SEMA8_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x340) // 4340
#define WOX_MCU_CFG_LS_WOX_SEMA9_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x344) // 4344
#define WOX_MCU_CFG_LS_WOX_SEMA10_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x348) // 4348
#define WOX_MCU_CFG_LS_WOX_SEMA11_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x34C) // 434C
#define WOX_MCU_CFG_LS_WOX_SEMA12_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x350) // 4350
#define WOX_MCU_CFG_LS_WOX_SEMA13_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x354) // 4354
#define WOX_MCU_CFG_LS_WOX_SEMA14_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x358) // 4358
#define WOX_MCU_CFG_LS_WOX_SEMA15_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x35C) // 435C
#define WOX_MCU_CFG_LS_WOX_SEMA16_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x360) // 4360
#define WOX_MCU_CFG_LS_WOX_SEMA17_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x364) // 4364
#define WOX_MCU_CFG_LS_WOX_SEMA18_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x368) // 4368
#define WOX_MCU_CFG_LS_WOX_SEMA19_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x36C) // 436C
#define WOX_MCU_CFG_LS_WOX_SEMA20_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x370) // 4370
#define WOX_MCU_CFG_LS_WOX_SEMA21_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x374) // 4374
#define WOX_MCU_CFG_LS_WOX_SEMA22_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x378) // 4378
#define WOX_MCU_CFG_LS_WOX_SEMA23_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x37C) // 437C
#define WOX_MCU_CFG_LS_WOX_SEMA24_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x380) // 4380
#define WOX_MCU_CFG_LS_WOX_SEMA25_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x384) // 4384
#define WOX_MCU_CFG_LS_WOX_SEMA26_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x388) // 4388
#define WOX_MCU_CFG_LS_WOX_SEMA27_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x38C) // 438C
#define WOX_MCU_CFG_LS_WOX_SEMA28_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x390) // 4390
#define WOX_MCU_CFG_LS_WOX_SEMA29_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x394) // 4394
#define WOX_MCU_CFG_LS_WOX_SEMA30_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x398) // 4398
#define WOX_MCU_CFG_LS_WOX_SEMA31_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x39C) // 439C
#define WOX_MCU_CFG_LS_DBGSR_ADDR                              (WOX_MCU_CFG_LS_BASE + 0x400) // 4400
#define WOX_MCU_CFG_LS_DBGSR1_ADDR                             (WOX_MCU_CFG_LS_BASE + 0x404) // 4404
#define WOX_MCU_CFG_LS_DBGSR2_ADDR                             (WOX_MCU_CFG_LS_BASE + 0x408) // 4408
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_ADDR                       (WOX_MCU_CFG_LS_BASE + 0x0430) // 4430
#define WOX_MCU_CFG_LS_BUSHANGCR_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x0440) // 4440
#define WOX_MCU_CFG_LS_BUSHANGADDR_ADDR                        (WOX_MCU_CFG_LS_BASE + 0x0444) // 4444
#define WOX_MCU_CFG_LS_BUSHANGID_ADDR                          (WOX_MCU_CFG_LS_BASE + 0x044C) // 444C
#define WOX_MCU_CFG_LS_BUSHANGBUS_ADDR                         (WOX_MCU_CFG_LS_BASE + 0x0450) // 4450
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_MON_SEL_ADDR             (WOX_MCU_CFG_LS_BASE + 0x0910) // 4910
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_0_ADDR              (WOX_MCU_CFG_LS_BASE + 0x0914) // 4914
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_1_ADDR              (WOX_MCU_CFG_LS_BASE + 0x0918) // 4918




/* =====================================================================================

  ---HW_VER (0x15194000 + 0x000)---

    HW_VER[31..0]                - (RO) CONNSYS Version

 =====================================================================================*/
#define WOX_MCU_CFG_LS_HW_VER_HW_VER_ADDR                      WOX_MCU_CFG_LS_HW_VER_ADDR
#define WOX_MCU_CFG_LS_HW_VER_HW_VER_MASK                      0xFFFFFFFF                // HW_VER[31..0]
#define WOX_MCU_CFG_LS_HW_VER_HW_VER_SHFT                      0

/* =====================================================================================

  ---FW_VER (0x15194000 + 0x004)---

    FW_VER[31..0]                - (RO) Firmware Version

 =====================================================================================*/
#define WOX_MCU_CFG_LS_FW_VER_FW_VER_ADDR                      WOX_MCU_CFG_LS_FW_VER_ADDR
#define WOX_MCU_CFG_LS_FW_VER_FW_VER_MASK                      0xFFFFFFFF                // FW_VER[31..0]
#define WOX_MCU_CFG_LS_FW_VER_FW_VER_SHFT                      0

/* =====================================================================================

  ---CFG_DBG1 (0x15194000 + 0x00C)---

    DEBUG_N0_EN[0]               - (RW) 0: Disable
                                     1: Enable
    DEBUG_N1_EN[1]               - (RW) 0: Disable
                                     1: Enable
    DEBUG_N2_EN[2]               - (RW) 0: Disable
                                     1: Enable
    DEBUG_N3_EN[3]               - (RW) 0: Disable
                                     1: Enable
    JTAG_SEL_EN[4]               - (RW) 0: Disable
                                     1: Enable
    JTAG_SEL[5]                  - (RW) 0: 5 wire
                                     1: 2 wire
    RESERVED6[31..6]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_CFG_DBG1_JTAG_SEL_ADDR                  WOX_MCU_CFG_LS_CFG_DBG1_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG1_JTAG_SEL_MASK                  0x00000020                // JTAG_SEL[5]
#define WOX_MCU_CFG_LS_CFG_DBG1_JTAG_SEL_SHFT                  5
#define WOX_MCU_CFG_LS_CFG_DBG1_JTAG_SEL_EN_ADDR               WOX_MCU_CFG_LS_CFG_DBG1_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG1_JTAG_SEL_EN_MASK               0x00000010                // JTAG_SEL_EN[4]
#define WOX_MCU_CFG_LS_CFG_DBG1_JTAG_SEL_EN_SHFT               4
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N3_EN_ADDR               WOX_MCU_CFG_LS_CFG_DBG1_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N3_EN_MASK               0x00000008                // DEBUG_N3_EN[3]
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N3_EN_SHFT               3
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N2_EN_ADDR               WOX_MCU_CFG_LS_CFG_DBG1_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N2_EN_MASK               0x00000004                // DEBUG_N2_EN[2]
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N2_EN_SHFT               2
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N1_EN_ADDR               WOX_MCU_CFG_LS_CFG_DBG1_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N1_EN_MASK               0x00000002                // DEBUG_N1_EN[1]
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N1_EN_SHFT               1
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N0_EN_ADDR               WOX_MCU_CFG_LS_CFG_DBG1_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N0_EN_MASK               0x00000001                // DEBUG_N0_EN[0]
#define WOX_MCU_CFG_LS_CFG_DBG1_DEBUG_N0_EN_SHFT               0

/* =====================================================================================

  ---CFG_DBG2 (0x15194000 + 0x010)---

    DEBUG_L1_N0_MOD_SEL[7..0]    - (RW) Debug flag selection
    DEBUG_L1_N1_MOD_SEL[15..8]   - (RW) Debug flag selection
    DEBUG_L1_N2_MOD_SEL[23..16]  - (RW) Debug flag selection
    DEBUG_L1_N3_MOD_SEL[31..24]  - (RW) Debug flag selection

 =====================================================================================*/
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N3_MOD_SEL_ADDR       WOX_MCU_CFG_LS_CFG_DBG2_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N3_MOD_SEL_MASK       0xFF000000                // DEBUG_L1_N3_MOD_SEL[31..24]
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N3_MOD_SEL_SHFT       24
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N2_MOD_SEL_ADDR       WOX_MCU_CFG_LS_CFG_DBG2_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N2_MOD_SEL_MASK       0x00FF0000                // DEBUG_L1_N2_MOD_SEL[23..16]
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N2_MOD_SEL_SHFT       16
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N1_MOD_SEL_ADDR       WOX_MCU_CFG_LS_CFG_DBG2_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N1_MOD_SEL_MASK       0x0000FF00                // DEBUG_L1_N1_MOD_SEL[15..8]
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N1_MOD_SEL_SHFT       8
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N0_MOD_SEL_ADDR       WOX_MCU_CFG_LS_CFG_DBG2_ADDR
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N0_MOD_SEL_MASK       0x000000FF                // DEBUG_L1_N0_MOD_SEL[7..0]
#define WOX_MCU_CFG_LS_CFG_DBG2_DEBUG_L1_N0_MOD_SEL_SHFT       0

/* =====================================================================================

  ---WOX_MCCR (0x15194000 + 0x014)---

    RESERVED0[9..0]              - (RO) Reserved bits
    UART_DBG_STOP[11..10]        - (RO) UART_DBG STOP control
                                     Triggered by CR set and released by CR clear
    RESERVED12[31..12]           - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_MCCR_UART_DBG_STOP_ADDR             WOX_MCU_CFG_LS_WOX_MCCR_ADDR
#define WOX_MCU_CFG_LS_WOX_MCCR_UART_DBG_STOP_MASK             0x00000C00                // UART_DBG_STOP[11..10]
#define WOX_MCU_CFG_LS_WOX_MCCR_UART_DBG_STOP_SHFT             10

/* =====================================================================================

  ---WOX_MCCR_SET (0x15194000 + 0x018)---

    RESERVED0[9..0]              - (RO) Reserved bits
    UART_DBG[11..10]             - (W1S) UART_DBG_STOP Set. Write 1 to set stop
    RESERVED12[31..12]           - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_MCCR_SET_UART_DBG_ADDR              WOX_MCU_CFG_LS_WOX_MCCR_SET_ADDR
#define WOX_MCU_CFG_LS_WOX_MCCR_SET_UART_DBG_MASK              0x00000C00                // UART_DBG[11..10]
#define WOX_MCU_CFG_LS_WOX_MCCR_SET_UART_DBG_SHFT              10

/* =====================================================================================

  ---WOX_MCCR_CLR (0x15194000 + 0x01C)---

    RESERVED0[9..0]              - (RO) Reserved bits
    UART_DBG[11..10]             - (W1C) UART_DBG_STOP Clear. Write 1 to set clear
    RESERVED12[31..12]           - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_MCCR_CLR_UART_DBG_ADDR              WOX_MCU_CFG_LS_WOX_MCCR_CLR_ADDR
#define WOX_MCU_CFG_LS_WOX_MCCR_CLR_UART_DBG_MASK              0x00000C00                // UART_DBG[11..10]
#define WOX_MCU_CFG_LS_WOX_MCCR_CLR_UART_DBG_SHFT              10

/* =====================================================================================

  ---WOX_MCU_CFG_WO0_WO1 (0x15194000 + 0x050)---

    RESERVED0[4..0]              - (RO) Reserved bits
    WOX_CPU_RSTB[5]              - (RW) WOX CPU software reset (low active)
    RESERVED6[31..6]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_MCU_CFG_WO0_WO1_WOX_CPU_RSTB_ADDR   WOX_MCU_CFG_LS_WOX_MCU_CFG_WO0_WO1_ADDR
#define WOX_MCU_CFG_LS_WOX_MCU_CFG_WO0_WO1_WOX_CPU_RSTB_MASK   0x00000020                // WOX_CPU_RSTB[5]
#define WOX_MCU_CFG_LS_WOX_MCU_CFG_WO0_WO1_WOX_CPU_RSTB_SHFT   5

/* =====================================================================================

  ---WOX_BOOT_ADDR (0x15194000 + 0x060)---

    WOX_BOOT_ADDR[15..0]         - (RW) WOX CPU Boot address MSB
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_BOOT_ADDR_WOX_BOOT_ADDR_ADDR        WOX_MCU_CFG_LS_WOX_BOOT_ADDR_ADDR
#define WOX_MCU_CFG_LS_WOX_BOOT_ADDR_WOX_BOOT_ADDR_MASK        0x0000FFFF                // WOX_BOOT_ADDR[15..0]
#define WOX_MCU_CFG_LS_WOX_BOOT_ADDR_WOX_BOOT_ADDR_SHFT        0

/* =====================================================================================

  ---WOX_CFG_CTL2 (0x15194000 + 0x06C)---

    WOX_ILM_BOOT[0]              - (RW) WOX CPU ILM_BOOT enable
                                     0: Disable
                                     1: Enable
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_CFG_CTL2_WOX_ILM_BOOT_ADDR          WOX_MCU_CFG_LS_WOX_CFG_CTL2_ADDR
#define WOX_MCU_CFG_LS_WOX_CFG_CTL2_WOX_ILM_BOOT_MASK          0x00000001                // WOX_ILM_BOOT[0]
#define WOX_MCU_CFG_LS_WOX_CFG_CTL2_WOX_ILM_BOOT_SHFT          0

/* =====================================================================================

  ---WOX_GP_IRQ (0x15194000 + 0x080)---

    WO_GP_IRQ_B[0]               - (RW) WOX CPU GP_IRQ_B (low active)
                                     0: active
                                     1: inactive
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_GP_IRQ_WO_GP_IRQ_B_ADDR             WOX_MCU_CFG_LS_WOX_GP_IRQ_ADDR
#define WOX_MCU_CFG_LS_WOX_GP_IRQ_WO_GP_IRQ_B_MASK             0x00000001                // WO_GP_IRQ_B[0]
#define WOX_MCU_CFG_LS_WOX_GP_IRQ_WO_GP_IRQ_B_SHFT             0

/* =====================================================================================

  ---FPGA_RSV (0x15194000 + 0x100)---

    FPGA_RSV[31..0]              - (RW) FPGA reserve register

 =====================================================================================*/
#define WOX_MCU_CFG_LS_FPGA_RSV_FPGA_RSV_ADDR                  WOX_MCU_CFG_LS_FPGA_RSV_ADDR
#define WOX_MCU_CFG_LS_FPGA_RSV_FPGA_RSV_MASK                  0xFFFFFFFF                // FPGA_RSV[31..0]
#define WOX_MCU_CFG_LS_FPGA_RSV_FPGA_RSV_SHFT                  0

/* =====================================================================================

  ---RESERVE0 (0x15194000 + 0x150)---

    RESERVE0[31..0]              - (RW) RESERVE0

 =====================================================================================*/
#define WOX_MCU_CFG_LS_RESERVE0_RESERVE0_ADDR                  WOX_MCU_CFG_LS_RESERVE0_ADDR
#define WOX_MCU_CFG_LS_RESERVE0_RESERVE0_MASK                  0xFFFFFFFF                // RESERVE0[31..0]
#define WOX_MCU_CFG_LS_RESERVE0_RESERVE0_SHFT                  0

/* =====================================================================================

  ---WOX_COM_REG0 (0x15194000 + 0x200)---

    WOX_CON_REG0[31..0]          - (RW) WOX_MCUSYS COMMON register no.0

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG0_WOX_CON_REG0_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG0_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG0_WOX_CON_REG0_MASK          0xFFFFFFFF                // WOX_CON_REG0[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG0_WOX_CON_REG0_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG1 (0x15194000 + 0x204)---

    WOX_CON_REG1[31..0]          - (RW) WOX_MCUSYS COMMON register no.1

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG1_WOX_CON_REG1_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG1_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG1_WOX_CON_REG1_MASK          0xFFFFFFFF                // WOX_CON_REG1[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG1_WOX_CON_REG1_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG2 (0x15194000 + 0x208)---

    WOX_CON_REG2[31..0]          - (RW) WOX_MCUSYS COMMON register no.2

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG2_WOX_CON_REG2_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG2_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG2_WOX_CON_REG2_MASK          0xFFFFFFFF                // WOX_CON_REG2[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG2_WOX_CON_REG2_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG3 (0x15194000 + 0x20C)---

    WOX_CON_REG3[31..0]          - (RW) WOX_MCUSYS COMMON register no.3

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG3_WOX_CON_REG3_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG3_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG3_WOX_CON_REG3_MASK          0xFFFFFFFF                // WOX_CON_REG3[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG3_WOX_CON_REG3_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG4 (0x15194000 + 0x210)---

    WOX_CON_REG4[31..0]          - (RW) WOX_MCUSYS COMMON register no.4

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG4_WOX_CON_REG4_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG4_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG4_WOX_CON_REG4_MASK          0xFFFFFFFF                // WOX_CON_REG4[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG4_WOX_CON_REG4_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG5 (0x15194000 + 0x214)---

    WOX_CON_REG5[31..0]          - (RW) WOX_MCUSYS COMMON register no.5

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG5_WOX_CON_REG5_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG5_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG5_WOX_CON_REG5_MASK          0xFFFFFFFF                // WOX_CON_REG5[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG5_WOX_CON_REG5_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG6 (0x15194000 + 0x218)---

    WOX_CON_REG6[31..0]          - (RW) WOX_MCUSYS COMMON register no.6

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG6_WOX_CON_REG6_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG6_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG6_WOX_CON_REG6_MASK          0xFFFFFFFF                // WOX_CON_REG6[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG6_WOX_CON_REG6_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG7 (0x15194000 + 0x21C)---

    WOX_CON_REG7[31..0]          - (RW) WOX_MCUSYS COMMON register no.7

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG7_WOX_CON_REG7_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG7_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG7_WOX_CON_REG7_MASK          0xFFFFFFFF                // WOX_CON_REG7[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG7_WOX_CON_REG7_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG8 (0x15194000 + 0x220)---

    WOX_CON_REG8[31..0]          - (RW) WOX_MCUSYS COMMON register no.8

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG8_WOX_CON_REG8_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG8_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG8_WOX_CON_REG8_MASK          0xFFFFFFFF                // WOX_CON_REG8[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG8_WOX_CON_REG8_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG9 (0x15194000 + 0x224)---

    WOX_CON_REG9[31..0]          - (RW) WOX_MCUSYS COMMON register no.9

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG9_WOX_CON_REG9_ADDR          WOX_MCU_CFG_LS_WOX_COM_REG9_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG9_WOX_CON_REG9_MASK          0xFFFFFFFF                // WOX_CON_REG9[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG9_WOX_CON_REG9_SHFT          0

/* =====================================================================================

  ---WOX_COM_REG10 (0x15194000 + 0x228)---

    WOX_CON_REG10[31..0]         - (RW) WOX_MCUSYS COMMON register no.10

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG10_WOX_CON_REG10_ADDR        WOX_MCU_CFG_LS_WOX_COM_REG10_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG10_WOX_CON_REG10_MASK        0xFFFFFFFF                // WOX_CON_REG10[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG10_WOX_CON_REG10_SHFT        0

/* =====================================================================================

  ---WOX_COM_REG11 (0x15194000 + 0x22C)---

    WOX_CON_REG11[31..0]         - (RW) WOX_MCUSYS COMMON register no.11

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG11_WOX_CON_REG11_ADDR        WOX_MCU_CFG_LS_WOX_COM_REG11_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG11_WOX_CON_REG11_MASK        0xFFFFFFFF                // WOX_CON_REG11[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG11_WOX_CON_REG11_SHFT        0

/* =====================================================================================

  ---WOX_COM_REG12 (0x15194000 + 0x230)---

    WOX_CON_REG12[31..0]         - (RW) WOX_MCUSYS COMMON register no.12

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG12_WOX_CON_REG12_ADDR        WOX_MCU_CFG_LS_WOX_COM_REG12_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG12_WOX_CON_REG12_MASK        0xFFFFFFFF                // WOX_CON_REG12[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG12_WOX_CON_REG12_SHFT        0

/* =====================================================================================

  ---WOX_COM_REG13 (0x15194000 + 0x234)---

    WOX_CON_REG13[31..0]         - (RW) WOX_MCUSYS COMMON register no.13

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG13_WOX_CON_REG13_ADDR        WOX_MCU_CFG_LS_WOX_COM_REG13_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG13_WOX_CON_REG13_MASK        0xFFFFFFFF                // WOX_CON_REG13[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG13_WOX_CON_REG13_SHFT        0

/* =====================================================================================

  ---WOX_COM_REG14 (0x15194000 + 0x238)---

    WOX_CON_REG14[31..0]         - (RW) WOX_MCUSYS COMMON register no.14

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG14_WOX_CON_REG14_ADDR        WOX_MCU_CFG_LS_WOX_COM_REG14_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG14_WOX_CON_REG14_MASK        0xFFFFFFFF                // WOX_CON_REG14[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG14_WOX_CON_REG14_SHFT        0

/* =====================================================================================

  ---WOX_COM_REG15 (0x15194000 + 0x23C)---

    WOX_CON_REG15[31..0]         - (RW) WOX_MCUSYS COMMON register no.15

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_COM_REG15_WOX_CON_REG15_ADDR        WOX_MCU_CFG_LS_WOX_COM_REG15_ADDR
#define WOX_MCU_CFG_LS_WOX_COM_REG15_WOX_CON_REG15_MASK        0xFFFFFFFF                // WOX_CON_REG15[31..0]
#define WOX_MCU_CFG_LS_WOX_COM_REG15_WOX_CON_REG15_SHFT        0

/* =====================================================================================

  ---WOX_SEMA0 (0x15194000 + 0x320)---

    WOX_SEMA0[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA0_WOX_SEMA0_ADDR                WOX_MCU_CFG_LS_WOX_SEMA0_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA0_WOX_SEMA0_MASK                0x00000001                // WOX_SEMA0[0]
#define WOX_MCU_CFG_LS_WOX_SEMA0_WOX_SEMA0_SHFT                0

/* =====================================================================================

  ---WOX_SEMA1 (0x15194000 + 0x324)---

    WOX_SEMA1[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA1_WOX_SEMA1_ADDR                WOX_MCU_CFG_LS_WOX_SEMA1_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA1_WOX_SEMA1_MASK                0x00000001                // WOX_SEMA1[0]
#define WOX_MCU_CFG_LS_WOX_SEMA1_WOX_SEMA1_SHFT                0

/* =====================================================================================

  ---WOX_SEMA2 (0x15194000 + 0x328)---

    WOX_SEMA2[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA2_WOX_SEMA2_ADDR                WOX_MCU_CFG_LS_WOX_SEMA2_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA2_WOX_SEMA2_MASK                0x00000001                // WOX_SEMA2[0]
#define WOX_MCU_CFG_LS_WOX_SEMA2_WOX_SEMA2_SHFT                0

/* =====================================================================================

  ---WOX_SEMA3 (0x15194000 + 0x32C)---

    WOX_SEMA3[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA3_WOX_SEMA3_ADDR                WOX_MCU_CFG_LS_WOX_SEMA3_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA3_WOX_SEMA3_MASK                0x00000001                // WOX_SEMA3[0]
#define WOX_MCU_CFG_LS_WOX_SEMA3_WOX_SEMA3_SHFT                0

/* =====================================================================================

  ---WOX_SEMA4 (0x15194000 + 0x330)---

    WOX_SEMA4[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA4_WOX_SEMA4_ADDR                WOX_MCU_CFG_LS_WOX_SEMA4_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA4_WOX_SEMA4_MASK                0x00000001                // WOX_SEMA4[0]
#define WOX_MCU_CFG_LS_WOX_SEMA4_WOX_SEMA4_SHFT                0

/* =====================================================================================

  ---WOX_SEMA5 (0x15194000 + 0x334)---

    WOX_SEMA5[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA5_WOX_SEMA5_ADDR                WOX_MCU_CFG_LS_WOX_SEMA5_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA5_WOX_SEMA5_MASK                0x00000001                // WOX_SEMA5[0]
#define WOX_MCU_CFG_LS_WOX_SEMA5_WOX_SEMA5_SHFT                0

/* =====================================================================================

  ---WOX_SEMA6 (0x15194000 + 0x338)---

    WOX_SEMA6[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA6_WOX_SEMA6_ADDR                WOX_MCU_CFG_LS_WOX_SEMA6_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA6_WOX_SEMA6_MASK                0x00000001                // WOX_SEMA6[0]
#define WOX_MCU_CFG_LS_WOX_SEMA6_WOX_SEMA6_SHFT                0

/* =====================================================================================

  ---WOX_SEMA7 (0x15194000 + 0x33C)---

    WOX_SEMA7[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA7_WOX_SEMA7_ADDR                WOX_MCU_CFG_LS_WOX_SEMA7_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA7_WOX_SEMA7_MASK                0x00000001                // WOX_SEMA7[0]
#define WOX_MCU_CFG_LS_WOX_SEMA7_WOX_SEMA7_SHFT                0

/* =====================================================================================

  ---WOX_SEMA8 (0x15194000 + 0x340)---

    WOX_SEMA8[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA8_WOX_SEMA8_ADDR                WOX_MCU_CFG_LS_WOX_SEMA8_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA8_WOX_SEMA8_MASK                0x00000001                // WOX_SEMA8[0]
#define WOX_MCU_CFG_LS_WOX_SEMA8_WOX_SEMA8_SHFT                0

/* =====================================================================================

  ---WOX_SEMA9 (0x15194000 + 0x344)---

    WOX_SEMA9[0]                 - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA9_WOX_SEMA9_ADDR                WOX_MCU_CFG_LS_WOX_SEMA9_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA9_WOX_SEMA9_MASK                0x00000001                // WOX_SEMA9[0]
#define WOX_MCU_CFG_LS_WOX_SEMA9_WOX_SEMA9_SHFT                0

/* =====================================================================================

  ---WOX_SEMA10 (0x15194000 + 0x348)---

    WOX_SEMA10[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA10_WOX_SEMA10_ADDR              WOX_MCU_CFG_LS_WOX_SEMA10_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA10_WOX_SEMA10_MASK              0x00000001                // WOX_SEMA10[0]
#define WOX_MCU_CFG_LS_WOX_SEMA10_WOX_SEMA10_SHFT              0

/* =====================================================================================

  ---WOX_SEMA11 (0x15194000 + 0x34C)---

    WOX_SEMA11[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA11_WOX_SEMA11_ADDR              WOX_MCU_CFG_LS_WOX_SEMA11_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA11_WOX_SEMA11_MASK              0x00000001                // WOX_SEMA11[0]
#define WOX_MCU_CFG_LS_WOX_SEMA11_WOX_SEMA11_SHFT              0

/* =====================================================================================

  ---WOX_SEMA12 (0x15194000 + 0x350)---

    WOX_SEMA12[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA12_WOX_SEMA12_ADDR              WOX_MCU_CFG_LS_WOX_SEMA12_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA12_WOX_SEMA12_MASK              0x00000001                // WOX_SEMA12[0]
#define WOX_MCU_CFG_LS_WOX_SEMA12_WOX_SEMA12_SHFT              0

/* =====================================================================================

  ---WOX_SEMA13 (0x15194000 + 0x354)---

    WOX_SEMA13[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA13_WOX_SEMA13_ADDR              WOX_MCU_CFG_LS_WOX_SEMA13_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA13_WOX_SEMA13_MASK              0x00000001                // WOX_SEMA13[0]
#define WOX_MCU_CFG_LS_WOX_SEMA13_WOX_SEMA13_SHFT              0

/* =====================================================================================

  ---WOX_SEMA14 (0x15194000 + 0x358)---

    WOX_SEMA14[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA14_WOX_SEMA14_ADDR              WOX_MCU_CFG_LS_WOX_SEMA14_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA14_WOX_SEMA14_MASK              0x00000001                // WOX_SEMA14[0]
#define WOX_MCU_CFG_LS_WOX_SEMA14_WOX_SEMA14_SHFT              0

/* =====================================================================================

  ---WOX_SEMA15 (0x15194000 + 0x35C)---

    WOX_SEMA15[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA15_WOX_SEMA15_ADDR              WOX_MCU_CFG_LS_WOX_SEMA15_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA15_WOX_SEMA15_MASK              0x00000001                // WOX_SEMA15[0]
#define WOX_MCU_CFG_LS_WOX_SEMA15_WOX_SEMA15_SHFT              0

/* =====================================================================================

  ---WOX_SEMA16 (0x15194000 + 0x360)---

    WOX_SEMA16[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA16_WOX_SEMA16_ADDR              WOX_MCU_CFG_LS_WOX_SEMA16_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA16_WOX_SEMA16_MASK              0x00000001                // WOX_SEMA16[0]
#define WOX_MCU_CFG_LS_WOX_SEMA16_WOX_SEMA16_SHFT              0

/* =====================================================================================

  ---WOX_SEMA17 (0x15194000 + 0x364)---

    WOX_SEMA17[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA17_WOX_SEMA17_ADDR              WOX_MCU_CFG_LS_WOX_SEMA17_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA17_WOX_SEMA17_MASK              0x00000001                // WOX_SEMA17[0]
#define WOX_MCU_CFG_LS_WOX_SEMA17_WOX_SEMA17_SHFT              0

/* =====================================================================================

  ---WOX_SEMA18 (0x15194000 + 0x368)---

    WOX_SEMA18[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA18_WOX_SEMA18_ADDR              WOX_MCU_CFG_LS_WOX_SEMA18_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA18_WOX_SEMA18_MASK              0x00000001                // WOX_SEMA18[0]
#define WOX_MCU_CFG_LS_WOX_SEMA18_WOX_SEMA18_SHFT              0

/* =====================================================================================

  ---WOX_SEMA19 (0x15194000 + 0x36C)---

    WOX_SEMA19[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA19_WOX_SEMA19_ADDR              WOX_MCU_CFG_LS_WOX_SEMA19_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA19_WOX_SEMA19_MASK              0x00000001                // WOX_SEMA19[0]
#define WOX_MCU_CFG_LS_WOX_SEMA19_WOX_SEMA19_SHFT              0

/* =====================================================================================

  ---WOX_SEMA20 (0x15194000 + 0x370)---

    WOX_SEMA20[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA20_WOX_SEMA20_ADDR              WOX_MCU_CFG_LS_WOX_SEMA20_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA20_WOX_SEMA20_MASK              0x00000001                // WOX_SEMA20[0]
#define WOX_MCU_CFG_LS_WOX_SEMA20_WOX_SEMA20_SHFT              0

/* =====================================================================================

  ---WOX_SEMA21 (0x15194000 + 0x374)---

    WOX_SEMA21[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA21_WOX_SEMA21_ADDR              WOX_MCU_CFG_LS_WOX_SEMA21_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA21_WOX_SEMA21_MASK              0x00000001                // WOX_SEMA21[0]
#define WOX_MCU_CFG_LS_WOX_SEMA21_WOX_SEMA21_SHFT              0

/* =====================================================================================

  ---WOX_SEMA22 (0x15194000 + 0x378)---

    WOX_SEMA22[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA22_WOX_SEMA22_ADDR              WOX_MCU_CFG_LS_WOX_SEMA22_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA22_WOX_SEMA22_MASK              0x00000001                // WOX_SEMA22[0]
#define WOX_MCU_CFG_LS_WOX_SEMA22_WOX_SEMA22_SHFT              0

/* =====================================================================================

  ---WOX_SEMA23 (0x15194000 + 0x37C)---

    WOX_SEMA23[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA23_WOX_SEMA23_ADDR              WOX_MCU_CFG_LS_WOX_SEMA23_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA23_WOX_SEMA23_MASK              0x00000001                // WOX_SEMA23[0]
#define WOX_MCU_CFG_LS_WOX_SEMA23_WOX_SEMA23_SHFT              0

/* =====================================================================================

  ---WOX_SEMA24 (0x15194000 + 0x380)---

    WOX_SEMA24[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA24_WOX_SEMA24_ADDR              WOX_MCU_CFG_LS_WOX_SEMA24_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA24_WOX_SEMA24_MASK              0x00000001                // WOX_SEMA24[0]
#define WOX_MCU_CFG_LS_WOX_SEMA24_WOX_SEMA24_SHFT              0

/* =====================================================================================

  ---WOX_SEMA25 (0x15194000 + 0x384)---

    WOX_SEMA25[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA25_WOX_SEMA25_ADDR              WOX_MCU_CFG_LS_WOX_SEMA25_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA25_WOX_SEMA25_MASK              0x00000001                // WOX_SEMA25[0]
#define WOX_MCU_CFG_LS_WOX_SEMA25_WOX_SEMA25_SHFT              0

/* =====================================================================================

  ---WOX_SEMA26 (0x15194000 + 0x388)---

    WOX_SEMA26[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA26_WOX_SEMA26_ADDR              WOX_MCU_CFG_LS_WOX_SEMA26_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA26_WOX_SEMA26_MASK              0x00000001                // WOX_SEMA26[0]
#define WOX_MCU_CFG_LS_WOX_SEMA26_WOX_SEMA26_SHFT              0

/* =====================================================================================

  ---WOX_SEMA27 (0x15194000 + 0x38C)---

    WOX_SEMA27[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA27_WOX_SEMA27_ADDR              WOX_MCU_CFG_LS_WOX_SEMA27_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA27_WOX_SEMA27_MASK              0x00000001                // WOX_SEMA27[0]
#define WOX_MCU_CFG_LS_WOX_SEMA27_WOX_SEMA27_SHFT              0

/* =====================================================================================

  ---WOX_SEMA28 (0x15194000 + 0x390)---

    WOX_SEMA28[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA28_WOX_SEMA28_ADDR              WOX_MCU_CFG_LS_WOX_SEMA28_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA28_WOX_SEMA28_MASK              0x00000001                // WOX_SEMA28[0]
#define WOX_MCU_CFG_LS_WOX_SEMA28_WOX_SEMA28_SHFT              0

/* =====================================================================================

  ---WOX_SEMA29 (0x15194000 + 0x394)---

    WOX_SEMA29[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA29_WOX_SEMA29_ADDR              WOX_MCU_CFG_LS_WOX_SEMA29_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA29_WOX_SEMA29_MASK              0x00000001                // WOX_SEMA29[0]
#define WOX_MCU_CFG_LS_WOX_SEMA29_WOX_SEMA29_SHFT              0

/* =====================================================================================

  ---WOX_SEMA30 (0x15194000 + 0x398)---

    WOX_SEMA30[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA30_WOX_SEMA30_ADDR              WOX_MCU_CFG_LS_WOX_SEMA30_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA30_WOX_SEMA30_MASK              0x00000001                // WOX_SEMA30[0]
#define WOX_MCU_CFG_LS_WOX_SEMA30_WOX_SEMA30_SHFT              0

/* =====================================================================================

  ---WOX_SEMA31 (0x15194000 + 0x39C)---

    WOX_SEMA31[0]                - (W1SRC) WOX_MCUSYS SEMAPHORE register (Write 1 set, read clear)
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_WOX_SEMA31_WOX_SEMA31_ADDR              WOX_MCU_CFG_LS_WOX_SEMA31_ADDR
#define WOX_MCU_CFG_LS_WOX_SEMA31_WOX_SEMA31_MASK              0x00000001                // WOX_SEMA31[0]
#define WOX_MCU_CFG_LS_WOX_SEMA31_WOX_SEMA31_SHFT              0

/* =====================================================================================

  ---DBGSR (0x15194000 + 0x400)---

    DEBUG_SELECT[23..0]          - (RW) Internal debug selection
    RESERVED24[31..24]           - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_DBGSR_DEBUG_SELECT_ADDR                 WOX_MCU_CFG_LS_DBGSR_ADDR
#define WOX_MCU_CFG_LS_DBGSR_DEBUG_SELECT_MASK                 0x00FFFFFF                // DEBUG_SELECT[23..0]
#define WOX_MCU_CFG_LS_DBGSR_DEBUG_SELECT_SHFT                 0

/* =====================================================================================

  ---DBGSR1 (0x15194000 + 0x404)---

    DEBUG_SELECT1[7..0]          - (RW) Internal debug selection1
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_DBGSR1_DEBUG_SELECT1_ADDR               WOX_MCU_CFG_LS_DBGSR1_ADDR
#define WOX_MCU_CFG_LS_DBGSR1_DEBUG_SELECT1_MASK               0x000000FF                // DEBUG_SELECT1[7..0]
#define WOX_MCU_CFG_LS_DBGSR1_DEBUG_SELECT1_SHFT               0

/* =====================================================================================

  ---DBGSR2 (0x15194000 + 0x408)---

    DEBUG_SELECT2[31..0]         - (RW) Internal debug selection2

 =====================================================================================*/
#define WOX_MCU_CFG_LS_DBGSR2_DEBUG_SELECT2_ADDR               WOX_MCU_CFG_LS_DBGSR2_ADDR
#define WOX_MCU_CFG_LS_DBGSR2_DEBUG_SELECT2_MASK               0xFFFFFFFF                // DEBUG_SELECT2[31..0]
#define WOX_MCU_CFG_LS_DBGSR2_DEBUG_SELECT2_SHFT               0

/* =====================================================================================

  ---BUSHANGCTRLA (0x15194000 + 0x0430)---

    RESERVED0[3..0]              - (RO) Reserved bits
    BUS_HANG_HBURST[6..4]        - (RO) bus hang hburst
    BUS_HANG_WRITE[7]            - (RO) bus hang hwrite/pwrite
    BUS_HANG_HTRANS[9..8]        - (RO) bus hang htrans
    RESERVED10[31..10]           - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_BUS_HANG_HTRANS_ADDR       WOX_MCU_CFG_LS_BUSHANGCTRLA_ADDR
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_BUS_HANG_HTRANS_MASK       0x00000300                // BUS_HANG_HTRANS[9..8]
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_BUS_HANG_HTRANS_SHFT       8
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_BUS_HANG_WRITE_ADDR        WOX_MCU_CFG_LS_BUSHANGCTRLA_ADDR
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_BUS_HANG_WRITE_MASK        0x00000080                // BUS_HANG_WRITE[7]
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_BUS_HANG_WRITE_SHFT        7
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_BUS_HANG_HBURST_ADDR       WOX_MCU_CFG_LS_BUSHANGCTRLA_ADDR
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_BUS_HANG_HBURST_MASK       0x00000070                // BUS_HANG_HBURST[6..4]
#define WOX_MCU_CFG_LS_BUSHANGCTRLA_BUS_HANG_HBURST_SHFT       4

/* =====================================================================================

  ---BUSHANGCR (0x15194000 + 0x0440)---

    BUS_HANG_TIME_LIMIT[7..0]    - (RW) Internal bus debug time limit
                                     The total hanging cycle count is a 32-bit value. BUS_HANG_TIME_LIMIT specifies the MSB of total hanging cycle count, that is:
                                     Total hanging cycle count = { BUS_HANG_TIME_LIMIT, 0x80000}
                                     For example:
                                     If BUS_HANG_TIME_LIMIT was set to 0x10, then total hanging cycle count will be 0x1080000, which means when bus was hanging for 0x1080000 cycles, an interrupt will be triggered
    RESERVED8[28..8]             - (RO) Reserved bits
    BUS_HANG_IRQ_CLR[29]         - (RW)  xxx 
    BUS_HANG_SLV_HREADY_SEL[30]  - (RW) Internal bus hang force slv_hready selection
                                     1'b0: revise ahb slave hready
                                     1'b1: force bus layer
    BUS_HANG_DEBUG_EN[31]        - (RW) Internal bus debug enable

 =====================================================================================*/
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_DEBUG_EN_ADDR        WOX_MCU_CFG_LS_BUSHANGCR_ADDR
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_DEBUG_EN_MASK        0x80000000                // BUS_HANG_DEBUG_EN[31]
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_DEBUG_EN_SHFT        31
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_SLV_HREADY_SEL_ADDR  WOX_MCU_CFG_LS_BUSHANGCR_ADDR
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_SLV_HREADY_SEL_MASK  0x40000000                // BUS_HANG_SLV_HREADY_SEL[30]
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_SLV_HREADY_SEL_SHFT  30
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_IRQ_CLR_ADDR         WOX_MCU_CFG_LS_BUSHANGCR_ADDR
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_IRQ_CLR_MASK         0x20000000                // BUS_HANG_IRQ_CLR[29]
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_IRQ_CLR_SHFT         29
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_TIME_LIMIT_ADDR      WOX_MCU_CFG_LS_BUSHANGCR_ADDR
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_TIME_LIMIT_MASK      0x000000FF                // BUS_HANG_TIME_LIMIT[7..0]
#define WOX_MCU_CFG_LS_BUSHANGCR_BUS_HANG_TIME_LIMIT_SHFT      0

/* =====================================================================================

  ---BUSHANGADDR (0x15194000 + 0x0444)---

    AHB_TIMEOUT_HADDR_LATCH[31..0] - (RO) Internal bus hang address

 =====================================================================================*/
#define WOX_MCU_CFG_LS_BUSHANGADDR_AHB_TIMEOUT_HADDR_LATCH_ADDR WOX_MCU_CFG_LS_BUSHANGADDR_ADDR
#define WOX_MCU_CFG_LS_BUSHANGADDR_AHB_TIMEOUT_HADDR_LATCH_MASK 0xFFFFFFFF                // AHB_TIMEOUT_HADDR_LATCH[31..0]
#define WOX_MCU_CFG_LS_BUSHANGADDR_AHB_TIMEOUT_HADDR_LATCH_SHFT 0

/* =====================================================================================

  ---BUSHANGID (0x15194000 + 0x044C)---

    BUS_HANG_ID[9..0]            - (RO) bus master id record when bus hang
    RESERVED10[31..10]           - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_BUSHANGID_BUS_HANG_ID_ADDR              WOX_MCU_CFG_LS_BUSHANGID_ADDR
#define WOX_MCU_CFG_LS_BUSHANGID_BUS_HANG_ID_MASK              0x000003FF                // BUS_HANG_ID[9..0]
#define WOX_MCU_CFG_LS_BUSHANGID_BUS_HANG_ID_SHFT              0

/* =====================================================================================

  ---BUSHANGBUS (0x15194000 + 0x0450)---

    BUS_HANG_BUS[31..0]          - (RO) indicate which bus is hang,
                                     [0]: s33, aximon
                                     [1]: s35, axidma
                                     [2]: s18, WOX_TOP_MISC_OFF
                                     [3]: s10, mcu_cfg_on
                                     [4]: s11, WO0_cirq
                                     [5]: s12, WO0_gpt
                                     [6]: s13, WO0_wdt
                                     [7]: s14, WO1_cirq
                                     [8]: s15, WO1_gpt
                                     [9]: s16, WO1_wdt

 =====================================================================================*/
#define WOX_MCU_CFG_LS_BUSHANGBUS_BUS_HANG_BUS_ADDR            WOX_MCU_CFG_LS_BUSHANGBUS_ADDR
#define WOX_MCU_CFG_LS_BUSHANGBUS_BUS_HANG_BUS_MASK            0xFFFFFFFF                // BUS_HANG_BUS[31..0]
#define WOX_MCU_CFG_LS_BUSHANGBUS_BUS_HANG_BUS_SHFT            0

/* =====================================================================================

  ---VDNR_BUS_DEBUG_MON_SEL (0x15194000 + 0x0910)---

    VDNR_BUS_DEBUG_MON_SEL[31..0] - (RW) BUS VDNR debug mon select control

 =====================================================================================*/
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_MON_SEL_VDNR_BUS_DEBUG_MON_SEL_ADDR WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_MON_SEL_ADDR
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_MON_SEL_VDNR_BUS_DEBUG_MON_SEL_MASK 0xFFFFFFFF                // VDNR_BUS_DEBUG_MON_SEL[31..0]
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_MON_SEL_VDNR_BUS_DEBUG_MON_SEL_SHFT 0

/* =====================================================================================

  ---VDNR_BUS_DEBUG_CTRL_0 (0x15194000 + 0x0914)---

    VDNR_DEBUG_CTRL_AO_DEBUGSYS_CTRL[31..0] - (RW) VDNR_DEBUG_CTRL_AO_DEBUGSYS_CTRL

 =====================================================================================*/
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_0_VDNR_DEBUG_CTRL_AO_DEBUGSYS_CTRL_ADDR WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_0_ADDR
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_0_VDNR_DEBUG_CTRL_AO_DEBUGSYS_CTRL_MASK 0xFFFFFFFF                // VDNR_DEBUG_CTRL_AO_DEBUGSYS_CTRL[31..0]
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_0_VDNR_DEBUG_CTRL_AO_DEBUGSYS_CTRL_SHFT 0

/* =====================================================================================

  ---VDNR_BUS_DEBUG_CTRL_1 (0x15194000 + 0x0918)---

    VDNR_DEBUG_CTRL_AO_IO_CTRL[7..0] - (RW) VDNR_DEBUG_CTRL_AO_IO_CTRL
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_1_VDNR_DEBUG_CTRL_AO_IO_CTRL_ADDR WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_1_ADDR
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_1_VDNR_DEBUG_CTRL_AO_IO_CTRL_MASK 0x000000FF                // VDNR_DEBUG_CTRL_AO_IO_CTRL[7..0]
#define WOX_MCU_CFG_LS_VDNR_BUS_DEBUG_CTRL_1_VDNR_DEBUG_CTRL_AO_IO_CTRL_SHFT 0

#ifdef __cplusplus
}
#endif

#endif // __WOX_MCU_CFG_LS_REGS_H__
