# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2019 - 2020 Intel Corporation.

obj-$(CONFIG_INTEL_NP_NET_CORE) += dpm/
obj-$(CONFIG_INTEL_NP_NET_CORE) += umt/
obj-$(CONFIG_INTEL_MIB_COUNTERS) += mib_counters/
obj-$(CONFIG_PON_QOS) += pon_qos/
