#ifndef __INTEL_GSWSS_H__
#define __INTEL_GSWSS_H__

/* Auxiliary Timestamp Trigger */
#define INTEL_GSWSS_AUX_TRIG_PONPPS		0
#define INTEL_GSWSS_AUX_TRIG_XGMAC2PPS		3
#define INTEL_GSWSS_AUX_TRIG_XGMAC3PPS		4
#define INTEL_GSWSS_AUX_TRIG_XGMAC4PPS		5
#define INTEL_GSWSS_AUX_TRIG_PONPP100US		6
#define INTEL_GSWSS_AUX_TRIG_EXTPPS0		8
#define INTEL_GSWSS_AUX_TRIG_EXTPPS1		9
#define INTEL_GSWSS_AUX_TRIG_SW			10

/* Reference Time */
#define INTEL_GSWSS_REFTIME_XGMAC2		3
#define INTEL_GSWSS_REFTIME_XGMAC3		4
#define INTEL_GSWSS_REFTIME_XGMAC4		5

/* PPS Master */
#define INTEL_GSWSS_PPS_PON			0
#define INTEL_GSWSS_PPS_XGMAC2			3
#define INTEL_GSWSS_PPS_XGMAC3			4
#define INTEL_GSWSS_PPS_XGMAC4			5
#define INTEL_GSWSS_PPS_SW			7

#endif	/* __INTEL_GSWSS_H__ */

