#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# platform driver
ccflags-y += -I../inc
snd-soc-procslic-patch-objs := si3218x_patch_A_2017MAY25.o

obj-$(CONFIG_SND_SOC_SI3218X) += snd-soc-proslic-patch.o
