include $(abs_top_srcdir)/Makefile.am.kbuild

lib-y := \
		 $(driver_rflib_shared_builddir)/mtlk_eeprom.o \
		 $(driver_rflib_shared_builddir)/eeprom_gpio.o \
		 $(driver_rflib_shared_builddir)/eeprom_irbd.o \
		 $(driver_rflib_shared_builddir)/cis_manager.o \
		 $(driver_rflib_shared_builddir)/mtlk_tpcv4.o \
		 $(driver_rflib_shared_builddir)/mtlk_gpl_helper.o

ifeq ($(CONFIG_RF_MANAGEMENT_MTLK),y)
  $(warning RF Lib: Metalink RF MGMT is ON)
  lib-y += $(driver_rflib_shared_builddir)/mtlk_rfmgmt.o
else
  $(warning RF Lib: Metalink RF MGMT is OFF)
endif

# Include extended debug info regardless current Linux kernel configuration.
# This is required for WLAN logger purposes.
# For this, unset DEBUG_INFO_REDUCED even if it is defined in Linux ".config" file.
#
DEBUG_INFO_REDUCED :=

EXTRA_CFLAGS += -g \
                -I$(abs_driver_rflib_shared_srcdir) \
                -I$(abs_driver_rflib_linux_srcdir) \
                -I$(abs_driver_shared_srcdir) \
                -I$(abs_wireless_shared_srcdir) \
                -I$(abs_fw_shared_srcdir) \
                -I$(abs_tools_srcdir)/mtidl \
                -I$(abs_rtlogger_shared_srcdir) \
                -I$(abs_driver_shared_srcdir) \
                -I$(abs_driver_linux_srcdir) \
                -I$(abs_tools_shared_srcdir) \
                -I$(abs_root_driver_shared_srcdir)

logger_origin_name = rflib
logger_binary_name = mtlk.o
logger_origin_id = 2

include $(abs_top_srcdir)/Makefile.am.module_helper
