#
# Copyright (C) Metalink Broadband 2007
#
# Module Name:
#   makefile.
#
# $Id$
#

!if "$(DDK_TARGET_OS)"=="WinLH"
!   INCLUDE $(NTMAKEENV)\makefile.def
!else
!   message Unknown Target Environment: $(DDK_TARGET_OS)
!endif
