/* client functions auto-generated by pidl */

#include "includes.h"
#include <tevent.h>
#include "lib/util/tevent_ntstatus.h"
#include "autoconf/librpc/gen_ndr/ndr_audiosrv.h"
#include "autoconf/librpc/gen_ndr/ndr_audiosrv_c.h"

/* audiosrv - client functions generated by pidl */

