/* client functions auto-generated by pidl */

#include "includes.h"
#include <tevent.h>
#include "lib/util/tevent_ntstatus.h"
#include "autoconf/librpc/gen_ndr/ndr_ioctl.h"
#include "autoconf/librpc/gen_ndr/ndr_ioctl_c.h"

/* copychunk - client functions generated by pidl */

