# SPDX-License-Identifier: GPL-2.0-only
obj-m := mt_wifi.o mtk_warp.o mtk_warp_proxy.o conninfra.o
#obj-m := conninfra.o
mt_wifi-objs := mt_wifi_mt7981.o
mtk_warp-objs := mtk_warp_mt7981.o
mtk_warp_proxy-objs := mtk_warp_proxy_mt7981.o
conninfra-objs := conninfra_mt7981.o

