#define GID_ABMANAGER            1
#define GID_ALGO                 2
#define GID_ANALYZER             3
#define GID_AUX                  4
#define GID_BEACON_MAN           5
#define GID_BITRATE              6
#define GID_CCR_COMMON           7
#define GID_CCR_PCIE             8
#define GID_CFG80211             9
#define GID_CIS                 10
#define GID_CLIPBOARD           11
#define GID_COC                 12
#define GID_COMMON_CORE         13
#define GID_COMPAT              14
#define GID_CORE                15
#define GID_CORE_CONFIG         16
#define GID_CPU_STAT            17
#define GID_DATAEX              18
#define GID_DFFW                19
#define GID_DFGLINUX            20
#define GID_DFLINUX             21
#define GID_DFUSER              22
#define GID_DUT_CORE            23
#define GID_EEPROM              24
#define GID_ETH_PARSER          25
#define GID_FRAME               26
#define GID_HS20                27
#define GID_HWHAL               28
#define GID_HWMMB               29
#define GID_IPERF_DEBUG         30
#define GID_IRB                 31
#define GID_LOG                 32
#define GID_LOGDRV              33
#define GID_MAC80211            34
#define GID_MCAST               35
#define GID_MEM_LEAK            36
#define GID_MMBDRV              37
#define GID_MTLK_CCR_DEFS       38
#define GID_MTLKCDEV            39
#define GID_MTLKHASH            40
#define GID_MTLKHASH_IEEE_ADDR  41
#define GID_MTLKIRBAHASH        42
#define GID_MTLK_LIST           43
#define GID_MTLKNDEV            44
#define GID_MTLK_OSAL           45
#define GID_MTLK_PACKETS        46
#define GID_MTLKSTARTUP         47
#define GID_NBUF                48
#define GID_NBUFSTATS           49
#define GID_NLMSGS              50
#define GID_OBJPOOL             51
#define GID_OSAL                52
#define GID_PCOC                53
#define GID_PDB                 54
#define GID_PROCAUX             55
#define GID_PROGMODEL           56
#define GID_PSDB                57
#define GID_QOS                 58
#define GID_RECOVERY            59
#define GID_ROOT                60
#define GID_SCAN_SUPPORT        61
#define GID_SERIALIZER          62
#define GID_SPRINTF             63
#define GID_STADB               64
#define GID_TA                  65
#define GID_TXMM                66
#define GID_UTILS               67
#define GID_VAPM                68
#define GID_VENDOR_CMD          69
#define GID_WAVE_RADIO          70
#define GID_WDS                 71
#define GID_WSS                 72
#define GID_THERMAL             73
