#define GID_ALGO                 1
#define GID_ARGV_PARSER          2
#define GID_ARPHELPER            3
#define GID_BCLSOCKSERVER        4
#define GID_CLI                  5
#define GID_CQUEUE               6
#define GID_DATAEX               7
#define GID_DB                   8
#define GID_DRIVER_API           9
#define GID_DRVHLPR             10
#define GID_DUMP_HANDLER        11
#define GID_DUT_MSG_CLB         12
#define GID_DUTSERVER           13
#define GID_DUT_SOCKETS         14
#define GID_DUT_SRV_DRIVER_API  15
#define GID_DUT_SRV_HOST_IF     16
#define GID_DUT_SRV_UTEST       17
#define GID_IRB                 18
#define GID_LEDSCTRL            19
#define GID_LOG                 20
#define GID_LOGSERVER           21
#define GID_LOGSRV_UTILS        22
#define GID_MAIN_DBG_SERVER     23
#define GID_MEM_LEAK            24
#define GID_MTLK_CLI            25
#define GID_MTLK_CLI_SERVER     26
#define GID_MTLKCONTAINER       27
#define GID_MTLKHASH            28
#define GID_MTLKIRBA            29
#define GID_MTLKIRBAHASH        30
#define GID_MTLK_LIST           31
#define GID_MTLKNLINK           32
#define GID_MTLKSHANDLER        33
#define GID_MTLK_SOCKET         34
#define GID_MTLKSTARTUP         35
#define GID_MT_TFTP             36
#define GID_NET                 37
#define GID_OBJPOOL             38
#define GID_OSAL                39
#define GID_PROTO_DRV           40
#define GID_PROTO_LG            41
#define GID_RTLOG_APP           42
#define GID_STRTOK              43
#define GID_UTILS               44
#define GID_WPSSCTRL            45
#define GID_WHM_HANDLER         46
