# SPDX-License-Identifier: GPL-2.0-only
#obj-m += mt_wifi.o mtk_warp.o mtk_warp_proxy.o conninfra.o
obj-m += conninfra.o
#mt_wifi-objs += ./mt_wifi.obj
#mtk_warp-objs += ./mtk_warp.obj
#mtk_warp_proxy-objs += ./mtk_warp_proxy.obj
conninfra-objs += ./conninfra.obj

