# SPDX-License-Identifier: GPL-2.0

# platform driver
snd-soc-mt7986-afe-objs := \
	mt7986-afe-pcm.o \
	mt7986-dai-etdm.o

obj-$(CONFIG_SND_SOC_MT7986) += snd-soc-mt7986-afe.o
obj-$(CONFIG_SND_SOC_MT7986_WM8960) += mt7986-wm8960.o
obj-$(CONFIG_SND_SOC_MT7986_SI3218X) += mt7986-si3218x.o
