/* List of HW D2 dependent registers */

/*  Block 1: HOST_IF_IRQS registers HOST_IRQ_MASK etc
 *  Block 2: HOST_IF_ACC  registers HOST_MAC_MAILBOX_ACCUM_ADD/COUNT/SUM
 *  Both blocks are defined as HOST_IF and accesible via HOST_IF_REG_FILE
 */

#define HOST_IF_IRQS_BAR0   HOST_IF_REG_FILE_OFFSET_FROM_BAR0
#define HOST_IF_ACC_BAR0    HOST_IF_REG_FILE_OFFSET_FROM_BAR0

/* Shared memory offset */
#define SHRAM_WRITABLE_OFFSET  SHARED_RAM_WHITE_OFFSET_FROM_BAR0

#define _PCIEG6_HW_DEPEND_REGS_LIST_ \
    /* HOST_IF_IRQS <-- HOST_IF (moved from MAC_GENERAL) */ \
    _HW_REG_DEF_(HOST_IF_IRQS, HOST_IF, HOST_IRQ_MASK)          \
    _HW_REG_DEF_(HOST_IF_IRQS, HOST_IF, HOST_IRQ_STATUS)        \
    _HW_REG_DEF_(HOST_IF_IRQS, HOST_IF, NPU2UPI_INTERRUPT_SET)  \
    _HW_REG_DEF_(HOST_IF_IRQS, HOST_IF, PHI_INTERRUPT_CLEAR)    \
    /* HOST_IF_ACC <-- HOST_IF (moved from HOST_IF_ACC) */ \
    _HW_REG_DEF_(HOST_IF_ACC, HOST_IF, HOST_MAC_MAILBOX_ACCUM_ADD) \
    _HW_REG_DEF_(HOST_IF_ACC, HOST_IF, MAC_HOST_MAILBOX_ACCUM_COUNT) \
    _HW_REG_DEF_(HOST_IF_ACC, HOST_IF, MAC_HOST_MAILBOX_ACCUM_SUB) \

