#
# $Id$
# This include file holds pathes for binaries produced by build
#

MTLK_TOOLS_PATH          = ..\..\tools
MTLK_BIN_PATH            = wbuild\wbin\$(DDK_TARGET_OS)\$(DDKBUILDENV)
MTLK_UNITTEST_BIN_PATH   = windows\unittest\bin\$(DDK_TARGET_OS)\$(DDKBUILDENV)
MTLK_LIB_PATH            = wbuild\wlib\$(DDK_TARGET_OS)\$(DDKBUILDENV)
MTLK_TOOLS_BIN_PATH      = wbuild\tools\$(DDK_TARGET_OS)\$(DDKBUILDENV)
MTLK_TOOLS_LIB_PATH      = wbuild\tools\wlib\$(DDK_TARGET_OS)\$(DDKBUILDENV)
MTLK_DRV_HW_PATH         = windows\hw\$(HW_TYPE)
MTLK_DRV_CORE_PATH       = windows\core
MTLK_DRV_PEEK_PATH       = windows\peek
MTLK_SHARED_INC          = shared_inc
MTLK_SHARED_MAC          = ..\shared_mac