#! /bin/sh

if [ -f "/userfs/bin/tcapi" ]; then
	APPS_MOUNTED_PATH=`tcapi get Apps_Entry apps_mounted_path`
	APPS_INSTALL_FOLDER=`tcapi get Apps_Entry apps_install_folder`

else
	APPS_MOUNTED_PATH=`nvram get apps_mounted_path`
	APPS_INSTALL_FOLDER=`nvram get apps_install_folder`
fi

APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER

rm -rf $APPS_INSTALL_PATH/bin/avahi-daemon
rm -rf $APPS_INSTALL_PATH/etc/avahi-daemon.conf
rm -rf $APPS_INSTALL_PATH/etc/mt-daap.service
rm -rf $APPS_INSTALL_PATH/lib/libavahi-common.so.*
rm -rf $APPS_INSTALL_PATH/lib/libavahi-core.so.*
