/******************************************************************************

         Copyright (c) 2020, MaxLinear, Inc.
         Copyright 2016 - 2020 Intel Corporation
         Copyright 2015 - 2016 Lantiq Beteiligungs-GmbH & Co. KG
         Copyright 2009 - 2014 Lantiq Deutschland GmbH
         Copyright 2007 - 2008 Infineon Technologies AG

  For licensing information, see the file 'LICENSE' in the root folder of
  this software module.

*******************************************************************************/

/* List of HW registers */
/* Macro _HW_REG_DEF_ should be defined */
#define _PCIE_COMMON_HW_REGS_LIST_ \
    /* PCIe configuration */ \
    _HW_REG_DEF_(PCIE_CFG_REGS, PCIE_REGBLOCK, MSI_CAPABILITY) \
    /* Lower MACs */ \
    _HW_REG_DEF_(SYS_IF_LM0, EMERALD_ENV, MIPS_CTL)     \
    _HW_REG_DEF_(SYS_IF_LM0, EMERALD_ENV, SECURE_WRITE) \
    _HW_REG_DEF_(SYS_IF_LM1, EMERALD_ENV, MIPS_CTL)     \
    _HW_REG_DEF_(SYS_IF_LM1, EMERALD_ENV, SECURE_WRITE) \
    /* Upper MAC */ \
    _HW_REG_DEF_(SYS_IF_UM, EMERALD_ENV, CLOCK_SELECT)  \
    _HW_REG_DEF_(SYS_IF_UM, EMERALD_ENV, MIPS_CTL)      \
    _HW_REG_DEF_(SYS_IF_UM, EMERALD_ENV, PLL_CTL)       \
    _HW_REG_DEF_(SYS_IF_UM, EMERALD_ENV, PLL_DIV)       \
    _HW_REG_DEF_(SYS_IF_UM, EMERALD_ENV, PLL_EN)        \
    _HW_REG_DEF_(SYS_IF_UM, EMERALD_ENV, PLL_LOCK)      \
    _HW_REG_DEF_(SYS_IF_UM, EMERALD_ENV, SECURE_WRITE)  \
    _HW_REG_DEF_(SYS_IF_UM, EMERALD_ENV, SYSTEM_INFO)   \
    /* MAC General */ \
    _HW_REG_DEF_(MAC_GEN_REGS, MAC_GENERAL, HYP_MAC_TOP_GPI_INT) /* FPGA_VERSION */ \
    _HW_REG_DEF_(MAC_GEN_REGS, MAC_GENERAL, PHY_EXT_RESET)          \
    _HW_REG_DEF_(MAC_GEN_REGS, MAC_GENERAL, SPARE_CONFIG_D2A)       \
    _HW_REG_DEF_(MAC_GEN_REGS, MAC_GENERAL, FCSI_CTL)               \
    _HW_REG_DEF_(MAC_GEN_REGS, MAC_GENERAL, PHY_BAND_CONFIG)        \
    \
    _HW_REG_DEF_(MAC_HT_EXT, MAC_HT_EXTENSIONS, CLK_CONTROL_REG_DYN_EN) \
    /* SOC */ \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, EEPROM_SW_ACCESS)              \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, EFUSE_DATA)                    \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, EFUSE_ADDRESS)                 \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, EFUSE_CONTROL)                 \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, EFUSE_STATUS)                  \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, EFUSE_TIMER_CONFIG1)           \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, EFUSE_TIMER_CONFIG2)           \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, EFUSE_PCIE_FSM_OVR)            \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, EFUSE_PD) /* power down */     \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, GPIO_PULLUP)                   \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, SOFT_RESET)                    \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, PCIE_LEGACY_INT_ENA)           \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, PCIE_MSI_ENABLE)               \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, PCIE_MSI_INTR_MODE)            \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, PCIE_APPS_NS_CTRL)             \
    _HW_REG_DEF_(SOC_REGS, SOC_REGS, RCU_BOOT)                      \
    \
    _HW_REG_DEF_(PAC, PAC_RXC, RX_CONTROL)                          \
    \
    _HW_REG_DEF_(TSF_TIMER, PAC_TIM, TSF_TIMER_HIGH_RPORT)          \
    _HW_REG_DEF_(TSF_TIMER, PAC_TIM, TSF_TIMER_LOW_RPORT)           \
    \
    _HW_REG_DEF_(   PHY_RX_TD, PHY_RX_TD, PHY_PROGMODEL_VER)        \
    _HW_REG_DEF_(B0_PHY_RX_TD, PHY_RX_TD, PHY_RXTD_REG096)          \
    _HW_REG_DEF_(B1_PHY_RX_TD, PHY_RX_TD, PHY_RXTD_REG096)          \
    \
    _HW_REG_DEF_(PHY_RX_TD_IF, PHY_RX_TD_IF, PHY_RXTD_IF_FCSI_ACCESS) \
    _HW_REG_DEF_(PHY_RX_TD_IF, PHY_RX_TD_IF, PHY_RXTD_IF126)        \
    _HW_REG_DEF_(PHY_RX_TD_IF, PHY_RX_TD_IF, PHY_RXTD_IF127)        \
    _HW_REG_DEF_(PHY_RX_TD_IF, PHY_RX_TD_IF, PHY_RXTD_IF12C)        \
    _HW_REG_DEF_(PHY_RX_TD_IF, PHY_RX_TD_IF, PHY_RXTD_IF131)        \
    _HW_REG_DEF_(PHY_RX_TD_IF, PHY_RX_TD_IF, PHY_RXTD_IF136)        \
    \
    _HW_REG_DEF_(PHY_RXTD_ANT0, PHY_RXTD_ANT0, PHY_RXTD_ANT_REG4B)  \
    \
    _HW_REG_DEF_(B0_PHY_AGC_ANT0, PHY_AGC_ANT0, INBAND_RSSI_SYSTEM_GAIN_REG) \
    _HW_REG_DEF_(B1_PHY_AGC_ANT0, PHY_AGC_ANT0, INBAND_RSSI_SYSTEM_GAIN_REG) \
    _HW_REG_DEF_(B0_PHY_AGC_ANT0, PHY_AGC_ANT0, IB_POWER_REG)          \
    _HW_REG_DEF_(B1_PHY_AGC_ANT0, PHY_AGC_ANT0, IB_POWER_REG)          \


/*--- MACs and GenRiscs: offsets from bar0 and sizes ---*/

#define WAVE_PCIE_URAM_IRAM_START     (CPU_IRAM_OFFSET_FROM_BAR0)
#define WAVE_PCIE_URAM_IRAM_SIZE      (CPU_IRAM_SIZE)

#define WAVE_PCIE_IFCPU_IRAM_START    (MAC_GENRISC_HOST_IRAM_OFFSET_FROM_BAR0)
#define WAVE_PCIE_IFCPU_IRAM_SIZE     (MAC_GENRISC_HOST_IRAM_SIZE)

#define WAVE_PCIE_B0_TXCPU_IRAM_START (B0_MAC_GENRISC_TX_IRAM_OFFSET_FROM_BAR0)
#define WAVE_PCIE_B0_TXCPU_IRAM_SIZE  (B0_MAC_GENRISC_TX_IRAM_SIZE)
#define WAVE_PCIE_B1_TXCPU_IRAM_START (B1_MAC_GENRISC_TX_IRAM_OFFSET_FROM_BAR0)
#define WAVE_PCIE_B1_TXCPU_IRAM_SIZE  (B1_MAC_GENRISC_TX_IRAM_SIZE)

#define WAVE_PCIE_B0_RXCPU_IRAM_START (B0_MAC_GENRISC_RX_IRAM_OFFSET_FROM_BAR0)
#define WAVE_PCIE_B0_RXCPU_IRAM_SIZE  (B0_MAC_GENRISC_RX_IRAM_SIZE)
#define WAVE_PCIE_B1_RXCPU_IRAM_START (B1_MAC_GENRISC_RX_IRAM_OFFSET_FROM_BAR0)
#define WAVE_PCIE_B1_RXCPU_IRAM_SIZE  (B1_MAC_GENRISC_RX_IRAM_SIZE)

/*--- Register blocks: offsets from bar0 ---*/
#define SYS_IF_UM_BAR0              (SYSTEM_IF_UPPER_CPU_OFFSET_FROM_BAR0)
#define SYS_IF_LM0_BAR0             (SYSTEM_IF_LOWER_B0_CPU_OFFSET_FROM_BAR0)
#define SYS_IF_LM1_BAR0             (SYSTEM_IF_LOWER_B1_CPU_OFFSET_FROM_BAR0)

#define HOST_IF_BAR0                (HOST_IF_REG_FILE_OFFSET_FROM_BAR0)

#define MAC_GEN_REGS_BAR0           (MAC_GEN_REGFILE_OFFSET_FROM_BAR0)
#define MAC_HT_EXT_BAR0             (B0_MAC_HT_EXTENSIONS_OFFSET_FROM_BAR0)

#define SOC_REGS_BAR0               (TOP_REGBLOCK_OFFSET_FROM_BAR0)
#define PCIE_CFG_REGS_BAR0          (PCIE_DBI0_REGBLOCK_OFFSET_FROM_BAR0)

#define PAC_BAR0                    (B0_PAC_RXC_OFFSET_FROM_BAR0)
#define TSF_TIMER_BAR0              (B0_PAC_TIM_OFFSET_FROM_BAR0)

#define RAB_BAR0                    (B0_RAB_OFFSET_FROM_BAR0)

#define PHY_RX_TD_BAR0              (B0_PHY_RX_TD_OFFSET_FROM_BAR0)
#define B0_PHY_RX_TD_BAR0           (B0_PHY_RX_TD_OFFSET_FROM_BAR0)
#define B1_PHY_RX_TD_BAR0           (B1_PHY_RX_TD_OFFSET_FROM_BAR0)

#define B0_PHY_AGC_ANT0_BAR0        (B0_PHY_AGC_ANT0_OFFSET_FROM_BAR0)
#define B1_PHY_AGC_ANT0_BAR0        (B1_PHY_AGC_ANT0_OFFSET_FROM_BAR0)

/* FIXME: Progmodel version */
#define REG_PHY_RX_TD_PHY_PROGMODEL_VER     (PHY_RX_TD_BASE_ADDRESS + 0x8040)

/* FIXME: are not available ? */
#define     PCIE_REGBLOCK_BASE_ADDRESS                          0x0000
#define REG_PCIE_REGBLOCK_MSI_CAPABILITY                        0x0050
#define MSI_CAPABILITY_REGISTER_CAPABILITY_ID                   MTLK_BFIELD_INFO(0, 8)
#define MSI_CAPABILITY_REGISTER_NEXT_POINTER                    MTLK_BFIELD_INFO(8, 8)
#define MSI_CAPABILITY_REGISTER_CTRL_MSI_ENABLE                 MTLK_BFIELD_INFO(16, 1)
#define MSI_CAPABILITY_REGISTER_CTRL_MSI_DISABLED               0
#define MSI_CAPABILITY_REGISTER_CTRL_MSI_ENABLED                1

#define MSI_CAPABILITY_REGISTER_CTRL_MULTIPLE_MESSAGES_CAPABLE  MTLK_BFIELD_INFO(17, 3)
#define MSI_CAPABILITY_REGISTER_CTRL_MULTIPLE_MESSAGES_ENABLE   MTLK_BFIELD_INFO(20, 3)
#define MSI_CAPABILITY_REGISTER_CTRL_64BIT_ADDRESS_CAPABLE      MTLK_BFIELD_INFO(23, 1)

/* REG_PAC_RXC_RX_CONTROL (PAC_RX_CONTROL) */
#define PAC_RX_CONTROL_RXC_ENABLE                               1 /* bit0: rxcEnable */

/* REG_PHY_AGC_ANT0_IB_POWER_REG (PHY_AGC_ANT0_IB_POWER_REG) */
#define PHY_AGC_ANT0_IB_POWER_IBPOWER                           MTLK_BFIELD_INFO(0, 9)  /* IB power output (0.5 dB) */

/* REG_PHY_AGC_ANT0_INBAND_RSSI_SYSTEM_GAIN_REG (PHY_AGC_ANT0_INBAND_RSSI_SYSTEM_GAIN_REG) */
#define PHY_AGC_ANT0_INBAND_RSSI_SYSTEM_GAIN_REG_IBGAIN         MTLK_BFIELD_INFO(0, 9)  /* (0.5 dB) */

/* #include "HwRegs/Wave600/PhyRxTdAnt0Regs.h" */
#define PHY_RXTD_ANT0_BAR0                                      (B0_PHY_RXTD_ANT0_OFFSET_FROM_BAR0)
#define PHY_RXTD_ANT0_BASE_ADDRESS                              (B0_PHY_RXTD_ANT0_BASE_ADDR)

/* REG_PHY_RXTD_ANT0_PHY_RXTD_ANT_REG4B (PHY_RXTD_ANT0_PHY_RXTD_ANT_REG4B) */
#define REG_PHY_RXTD_ANT0_PHY_RXTD_ANT_REG4B                    (PHY_RXTD_ANT0_BASE_ADDRESS + 0x12C)
#define PHY_RXTD_ANT0_PHY_RXTD_ANT_REG4B_FCSI_MS_RESET_ANT_N    MTLK_BFIELD_INFO(0, 1)  /* fcsi_ms_reset_antennas_n */
#define PHY_RXTD_ANT0_PHY_RXTD_ANT_REG4B_FCSI_RF_RESET_N        MTLK_BFIELD_INFO(4, 1)  /* fcsi_rf_reset_n */

/* #include "HwRegs/Wave600/PhyRxTdIfRegs.h" */
#define PHY_RX_TD_IF_BAR0                                       (PHY_RX_TD_BAR0)
#define PHY_RX_TD_IF_BASE_ADDRESS                               (PHY_RX_TD_BASE_ADDRESS)

/* REG_PHY_RX_TD_IF_PHY_RXTD_IF_FCSI_ACCESS (PHY_RX_TD_IF_PHY_RXTD_IF_FCSI_ACCESS) */
#define REG_PHY_RX_TD_IF_PHY_RXTD_IF_FCSI_ACCESS                (PHY_RX_TD_IF_BASE_ADDRESS + 0x14A4)
#define PHY_RX_TD_IF_PHY_RXTD_IF_FCSI_ACCESS_FCSI_GR_ADDR       MTLK_BFIELD_INFO( 0, 7)
#define PHY_RX_TD_IF_PHY_RXTD_IF_FCSI_ACCESS_FCSI_GR_MASK       MTLK_BFIELD_INFO( 7, 5)
#define PHY_RX_TD_IF_PHY_RXTD_IF_FCSI_ACCESS_RESERVED0          MTLK_BFIELD_INFO(12, 1)
#define PHY_RX_TD_IF_PHY_RXTD_IF_FCSI_ACCESS_FCSI_GR_MS_ACCESS  MTLK_BFIELD_INFO(13, 1)
#define PHY_RX_TD_IF_PHY_RXTD_IF_FCSI_ACCESS_FCSI_GR_RF_ACCESS  MTLK_BFIELD_INFO(14, 1)
#define PHY_RX_TD_IF_PHY_RXTD_IF_FCSI_ACCESS_FCSI_GR_RD_WR      MTLK_BFIELD_INFO(15, 1)

/* REG_PHY_RX_TD_IF_PHY_RXTD_IF126 (PHY_RX_TD_IF_PHY_RXTD_IF126) */
#define REG_PHY_RX_TD_IF_PHY_RXTD_IF126                         (PHY_RX_TD_IF_BASE_ADDRESS + 0x1498)
#define PHY_RX_TD_IF_PHY_RXTD_IF126_FCSI_CLK_WR_DIVR_EXT_RF     MTLK_BFIELD_INFO(0,  6) /* fcsiClkWrDivrExtRf */
#define PHY_RX_TD_IF_PHY_RXTD_IF126_FCSI_CLK_RD_DIVR_EXT_RF     MTLK_BFIELD_INFO(8,  6) /* fcsiClkRdDivrExtRf */

/* REG_PHY_RX_TD_IF_PHY_RXTD_IF127 (PHY_RX_TD_IF_PHY_RXTD_IF127) */
#define REG_PHY_RX_TD_IF_PHY_RXTD_IF127                         (PHY_RX_TD_IF_BASE_ADDRESS + 0x149C)
#define PHY_RX_TD_IF_PHY_RXTD_IF127_FCSI_CLK_WR_DIVR_AFE        MTLK_BFIELD_INFO(0,  6) /* fcsiClkWrDivrAfe */
#define PHY_RX_TD_IF_PHY_RXTD_IF127_FCSI_CLK_RD_DIVR_AFE        MTLK_BFIELD_INFO(8,  6) /* fcsiClkRdDivrAfe */

/* REG_PHY_RX_TD_IF_PHY_RXTD_IF12C (PHY_RX_TD_IF_PHY_RXTD_IF12C) */
#define REG_PHY_RX_TD_IF_PHY_RXTD_IF12C                         (PHY_RX_TD_IF_BASE_ADDRESS + 0x14B0)
#define PHY_RX_TD_IF_PHY_RXTD_IF12C_FCSI_GR_WR_DATA             MTLK_BFIELD_INFO(0, 16) /* RW */

/* REG_PHY_RX_TD_IF_PHY_RXTD_IF131 (PHY_RX_TD_IF_PHY_RXTD_IF131) */
#define REG_PHY_RX_TD_IF_PHY_RXTD_IF131                         (PHY_RX_TD_IF_BASE_ADDRESS + 0x14C4)
#define PHY_RX_TD_IF_PHY_RXTD_IF131_FCSI_RD_DATA                MTLK_BFIELD_INFO(0, 16) /* RO */

/* REG_PHY_RX_TD_IF_PHY_RXTD_IF136 (PHY_RX_TD_IF_PHY_RXTD_IF136) */
#define REG_PHY_RX_TD_IF_PHY_RXTD_IF136                         (PHY_RX_TD_IF_BASE_ADDRESS + 0x14D8)
#define PHY_RX_TD_IF_PHY_RXTD_IF136_FCSI_BUSY                   MTLK_BFIELD_INFO(0, 1) /* RO */


/* MAC_GEN_REGS (REG_MAC_GENERAL) */

/*  REG_MAC_GENERAL_PHY_EXT_RESET (MAC_GEN_REGS_PHY_EXT_RESET) */
#define MAC_GEN_REGS_PHY_EXT_RESET_MAC_TO_PHY_BAND0_RESET_N     MTLK_BFIELD_INFO(0, 1)
#define MAC_GEN_REGS_PHY_EXT_RESET_MAC_TO_PHY_BAND1_RESET_N     MTLK_BFIELD_INFO(1, 1)

/* REG_MAC_GENERAL_SPARE_CONFIG_D2A (MAC_GEN_REGS_SPARE_CONFIG_D2A) */
#define MAC_GEN_REGS_SPARE_CONFIG_D2A_SPARE_CONFIG_D2A          MTLK_BFIELD_INFO(0, 8)

/* REG_MAC_GENERAL_FCSI_CTL */
#define MAC_GEN_REGS_FCSI_CTL_FCSI_MS_RESET_QC_D2A              MTLK_BFIELD_INFO(0, 1) /* fcsiMsRstqcD2A */
#define MAC_GEN_REGS_FCSI_CTL_FCSI_RF_RESET_QC_D2A              MTLK_BFIELD_INFO(1, 1) /* fcsiRfResetQcD2A */

/* REG_MAC_GENERAL_CLK_CONTROL_REG_DYN_EN */
#define MAC_GEN_REGS_CLK_CONTROL_REG_DYN_EN_Q_MANAGERS03        MTLK_BFIELD_INFO(0, 4) /* clkControlDynEnQManager0..3*/
#define MAC_GEN_REGS_CLK_CONTROL_REG_DYN_EN_Q_MANAGERS03_ENABLE 0xf

/* REG_MAC_GENERAL_PHY_BAND_CONFIG (MAC_GEN_REGS_PHY_BAND_CONFIG) */
#define MAC_GEN_REGS_PHY_BAND_CONFIG_B0_PHY_ACTIVE              MTLK_BFIELD_INFO(0, 1)
#define MAC_GEN_REGS_PHY_BAND_CONFIG_B1_PHY_ACTIVE              MTLK_BFIELD_INFO(1, 1)
#define MAC_GEN_REGS_PHY_BAND_CONFIG_FCSI_CEN_RESET_N           MTLK_BFIELD_INFO(2, 1)
#define MAC_GEN_REGS_PHY_BAND_CONFIG_FCSI_CEN_BLOCK_EN          MTLK_BFIELD_INFO(3, 1)

/* SOC_REGS_PCIE_MSI_INTR_MODE */
#define SOC_REGS_PCIE_MSI_INTR_MODE_PCIEMSIINTRMODE             MTLK_BFIELD_INFO(0, 2) /* pcieMsiIntrMode */

/* SOC_REGS_PCIE_LEGACY_INT_ENA */
#define SOC_REGS_PCIE_LEGACY_INT_ENA_LEG_ENABLE                 MTLK_BFIELD_INFO(0, 1) /* pcieLegacyIntEna */
#define PCIE_LEGACY_INT_DISABLED                                0
#define PCIE_LEGACY_INT_ENABLED                                 1

/* SOC_REGS_PCIE_MSI_ENABLE */
#define SOC_REGS_PCIE_MSI_ENABLE_VEN_MSI_ENABLE                 MTLK_BFIELD_INFO(0, 8) /* venMsiEna */
#define PCIE_MSI_DISABLED                                       0
#define PCIE_MSI_ENABLED                                        0xff


/* PLL control: REG_EMERALD_ENV_PLL_CTL (SYS_IF_UM_PLL_CTL) */
#define SYS_IF_UM_PLL_CTL_RESERVED0             MTLK_BFIELD_INFO(0, 7)
#define SYS_IF_UM_PLL_CTL_LCPLL_PUP_D2A         MTLK_BFIELD_INFO(7, 1) /* lcpllPupD2A */
#define SYS_IF_UM_PLL_CTL_LCPLL_RESETN_D2A      MTLK_BFIELD_INFO(8, 1) /* lcpllResetnD2A  PLL reset_n */
#define SYS_IF_UM_PLL_CTL_LCPLL_BYPASS_D2A      MTLK_BFIELD_INFO(9, 1) /* lcpllBypassD2A  PLL LDO disable */

#define SYS_IF_UM_PLL_CTL_LCPLL_PUP_D2A_DFLT    0 /* reset value */
#define SYS_IF_UM_PLL_CTL_LCPLL_RESETN_D2A_DFLT 0 /* reset value */
#define SYS_IF_UM_PLL_CTL_LCPLL_BYPASS_D2A_DFLT 0 /* reset value */

/* PLL lock:    REG_EMERALD_ENV_PLL_LOCK (SYS_IF_UM_PLL_LOCK) */
#define SYS_IF_UM_PLL_LOCK_PLL_LOCK             MTLK_BFIELD_INFO(0, 1) /* pllLock */

/* PLL divider: REG_EMERALD_ENV_PLL_DIV (SYS_IF_UM_PLL_DIV) */
#define SYS_IF_UM_PLL_DIV_TEST_CLK_DIV_D2A      MTLK_BFIELD_INFO(0, 2) /* testClkDivD2A */
#define SYS_IF_UM_PLL_DIV_WLAN_CLK_DIV_D2A      MTLK_BFIELD_INFO(2, 2) /* wlanClkDivD2A */
#define SYS_IF_UM_PLL_DIV_ADC_CLK_DIV_D2A       MTLK_BFIELD_INFO(4, 2) /* adcClkDivD2A  */
#define SYS_IF_UM_PLL_DIV_DAC_CLK_DIV_D2A       MTLK_BFIELD_INFO(6, 2) /* dacClkDivD2A  */
#define SYS_IF_UM_PLL_DIV_SSI_CLK_DIV_D2A       MTLK_BFIELD_INFO(8, 2) /* ssiClkDivD2A  */

#define REG_PCIE6_PLL_DIV_TEST_CLK_DIV_D2A_DEFAULT   0x00
#define REG_PCIE6_PLL_DIV_WLAN_CLK_DIV_D2A_DEFAULT   0x01
#define REG_PCIE6_PLL_DIV_ADC_CLK_DIV_D2A_DEFAULT    0x00
#define REG_PCIE6_PLL_DIV_DAC_CLK_DIV_D2A_DEFAULT    0x00
#define REG_PCIE6_PLL_DIV_SSI_CLK_DIV_D2A_DEFAULT    0x01

/* PLL enable clocks: REG_EMERALD_ENV_PLL_EN (SYS_IF_UM_PLL_EN) */
#define SYS_IF_UM_PLL_EN_TEST_CLK_PDN_D2A       MTLK_BFIELD_INFO(0, 1) /* testClkPdnD2A  Test clock power-down */
#define SYS_IF_UM_PLL_EN_WLAN_CLK_PDN_D2A       MTLK_BFIELD_INFO(1, 1) /* wlanClkPdnD2A  WLAN clock power-down */
#define SYS_IF_UM_PLL_EN_ADC_CLK_PDN_D2A        MTLK_BFIELD_INFO(2, 1) /* adcClkPdnD2A   ADC  clock power-down */
#define SYS_IF_UM_PLL_EN_DAC_CLK_PDN_D2A        MTLK_BFIELD_INFO(3, 1) /* dacClkPdnD2A   DAC  clock power-down */
#define SYS_IF_UM_PLL_EN_SSI_CLK_PDN_D2A        MTLK_BFIELD_INFO(4, 1) /* ssiClkPdnD2A   SSI  clock power-down */

#define REG_PCIE6_PLL_EN_TEST_CLK_PDN_D2A_DEFAULT    0x01
#define REG_PCIE6_PLL_EN_WLAN_CLK_PDN_D2A_DEFAULT    0x00
#define REG_PCIE6_PLL_EN_ADC_CLK_PDN_D2A_DEFAULT     0x00
#define REG_PCIE6_PLL_EN_DAC_CLK_PDN_D2A_DEFAULT     0x00
#define REG_PCIE6_PLL_EN_SSI_CLK_PDN_D2A_DEFAULT     0x01

/* Clock select: REG_EMERALD_ENV_CLOCK_SELECT (SYS_IF_UM_CLOCK_SELECT) */
#define SYS_IF_UM_CLOCK_SELECT_CPU_CLOCK_SELECT     MTLK_BFIELD_INFO(0, 2)
#define SYS_IF_UM_CLOCK_SELECT_CPU_CLOCK_SELECT_XO  (1)
#define SYS_IF_UM_CLOCK_SELECT_CPU_CLOCK_SELECT_PLL (2)


/*------ ABB and FW PHY libraries ------------------------*/

/* "wav600_A0/spectool2/CENTRAL_SYSTEM/c/central_fcsi/central_fcsi_regpkg.h" */

/* ICENTBIAS0 - BIAS_CONFIG */
#define CENTRAL_FCSI_ICENTBIAS0                             (0x00000040)
#define CENTRAL_FCSI_ICENTBIAS0__INIT                       (0x0080)
/* bias current trimming */
#define CENTRAL_FCSI_ICENTBIAS0_BIASTRIM                    MTLK_BFIELD_INFO(0, 4)
#define CENTRAL_FCSI_ICENTBIAS0_BIASTRIM__INIT              (0x0000)
/* ptat current trimming */
#define CENTRAL_FCSI_ICENTBIAS0_PTATTRIM                    MTLK_BFIELD_INFO(4, 4)
#define CENTRAL_FCSI_ICENTBIAS0_PTATTRIM__INIT              (0x0008)
/* reference voltage trimming */
#define CENTRAL_FCSI_ICENTBIAS0_VREFTRIM                    MTLK_BFIELD_INFO(8, 4)
#define CENTRAL_FCSI_ICENTBIAS0_VREFTRIM__INIT              (0x0000)

/* IVREG0V950 - VREG0V95FSYS_CONFIG */
#define CENTRAL_FCSI_IVREG0V950                             (0x00000045)
#define CENTRAL_FCSI_IVREG0V950__INIT                       (0x0008)
/* LDO output voltage trimming */
#define CENTRAL_FCSI_IVREG0V950_OUTTRIM                     MTLK_BFIELD_INFO(0, 4)
#define CENTRAL_FCSI_IVREG0V950_OUTTRIM__INIT               (0x0008)
#define CENTRAL_FCSI_IVREG0V950_OUTTRIM_0V982__VAL          (0x0008)
/* low power mode switch */
#define CENTRAL_FCSI_IVREG0V950_LP                          MTLK_BFIELD_INFO(6, 1)
#define CENTRAL_FCSI_IVREG0V950_LP__INIT                    (0x0000)
#define CENTRAL_FCSI_IVREG0V950_LP_OFF__VAL                 (0x0000)

/* ILDOCLKD0 - LDOCLKD_CONFIG */
#define CENTRAL_FCSI_ILDOCLKD0                              (0x00000047)
#define CENTRAL_FCSI_ILDOCLKD0__INIT                        (0x0008)
/* LDO output voltage trimming */
#define CENTRAL_FCSI_ILDOCLKD0_OUTTRIM                      MTLK_BFIELD_INFO(0, 4)
#define CENTRAL_FCSI_ILDOCLKD0_OUTTRIM__INIT                (0x0008)
#define CENTRAL_FCSI_ILDOCLKD0_OUTTRIM_0V982__VAL           (0x0008)

/* ILDOPLLREF0 - LDO0V95PLLREF_CONFIG */
#define CENTRAL_FCSI_ILDOPLLREF0                            (0x0000005C)
#define CENTRAL_FCSI_ILDOPLLREF0__INIT                      (0x0008)
/* LDO output voltage trimming */
#define CENTRAL_FCSI_ILDOPLLREF0_OUTTRIM                    MTLK_BFIELD_INFO(0, 4)
#define CENTRAL_FCSI_ILDOPLLREF0_OUTTRIM__INIT              (0x0008)
#define CENTRAL_FCSI_ILDOPLLREF0_OUTTRIM_0V982__VAL         (0x0008)
#define CENTRAL_FCSI_ILDOPLLREF0_OUTTRIM_0V951__VAL         (0x0005)

/* ILDOPLLPOST0 - LDO0V95PLLPOST_CONFIG */
#define CENTRAL_FCSI_ILDOPLLPOST0                           (0x0000005D)
#define CENTRAL_FCSI_ILDOPLLPOST0__INIT                     (0x0008)
/* LDO output voltage trimming */
#define CENTRAL_FCSI_ILDOPLLPOST0_OUTTRIM                    MTLK_BFIELD_INFO(0, 4)
#define CENTRAL_FCSI_ILDOPLLPOST0_OUTTRIM__INIT             (0x0008)
#define CENTRAL_FCSI_ILDOPLLPOST0_OUTTRIM_0V982__VAL        (0x0008)
#define CENTRAL_FCSI_ILDOPLLPOST0_OUTTRIM_0V951__VAL        (0x0005)

/* IVREG1V8HV0 - VREG1V8PLLHV_CONFIG */
#define CENTRAL_FCSI_IVREG1V8HV0                            (0x0000005E)
#define CENTRAL_FCSI_IVREG1V8HV0__INIT                      (0x0004)
/* output voltage trimming */
#define CENTRAL_FCSI_IVREG1V8HV0_OUTTRIM                    MTLK_BFIELD_INFO(0, 3)
#define CENTRAL_FCSI_IVREG1V8HV0_OUTTRIM__INIT              (0x0004)
#define CENTRAL_FCSI_IVREG1V8HV0_OUTTRIM_1V8__SVAL          (0x0004)

