#! /bin/sh

if [ -f "/userfs/bin/tcapi" ]; then
	APPS_MOUNTED_PATH=`tcapi get Apps_Entry apps_mounted_path`
	APPS_INSTALL_FOLDER=`tcapi get Apps_Entry apps_install_folder`
else
	APPS_MOUNTED_PATH=`nvram get apps_mounted_path`
	APPS_INSTALL_FOLDER=`nvram get apps_install_folder`
fi
APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER

mv -f /opt/tmp/bin/* $APPS_INSTALL_PATH/bin/
chmod -R 777 $APPS_INSTALL_PATH/bin










