#/******************************************************************************
#
#         Copyright (c) 2020, MaxLinear, Inc.
#         Copyright 2016 - 2020 Intel Corporation
#         Copyright 2015 - 2016 Lantiq Beteiligungs-GmbH & Co. KG
#         Copyright 2009 - 2014 Lantiq Deutschland GmbH
#         Copyright 2007 - 2008 Infineon Technologies AG
#
#  For licensing information, see the file 'LICENSE' in the root folder of
#  this software module.
#
#*******************************************************************************/

# Module Name:
#   makefile.
#
# $Id: $
#

!if "$(DDK_TARGET_OS)"=="WinXP"
!   INCLUDE $(NTMAKEENV)\makefile.def
!else
!   message Unknown Target Environment: $(DDK_TARGET_OS)
!endif
