ifeq ($(CONFIG_DIRECTCONNECT_DP_LGM),y)
	obj-m += dc_mode1-lgm.o
	dc_mode1-lgm-objs += dc_modex_ext.o
endif

ifeq ($(CONFIG_DIRECTCONNECT_DP_PRX300),y)
	obj-m += dc_mode1-prx300.o
	dc_mode1-prx300-objs += dc_modex_ext.o
endif
