#
#Makefile for intel specific clk
#

obj-$(CONFIG_PRX300_CLK) += clk-prx300.o clk-cgu.o clk-cgu-pll.o
obj-$(CONFIG_GRX500_CLK) += clk-grx500.o clk_api.o
obj-$(CONFIG_GRX330_CLK) += clk-grx330.o clk_api.o
obj-$(CONFIG_GRX200_CLK) += clk-grx200.o clk_api.o
