
###############################################################################
#         Copyright (c) 2020, MaxLinear, Inc.
#         Copyright 2016 - 2020 Intel Corporation
# 
#  For licensing information, see the file 'LICENSE' in the root folder of
#  this software module.
# 
###############################################################################

#CC:=gcc

##################################################
# For cross compile only
##################################################
export STAGING_DIR:=../../../../../../../openwrt/staging_dir/toolchain-mips_24kc+nomips16_gcc-8.3.0_musl
CC:=$(STAGING_DIR)/bin/mips-openwrt-linux-musl-gcc
CFLAGS:=-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts
CFLAGS+=-Wall -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security
CFLAGS+=-fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro -Wno-uninitialized -Wno-switch-unreachable
CFLAGS+=-I ../../include -I ../../../../../../openwrt/staging_dir/target-mips_24kc+nomips16_musl_axepoint_gw_sec/usr/include
LDFLAGS:=-L$(STAGING_DIR) -L ../../../../../../openwrt/staging_dir/target-mips_24kc+nomips16_musl_axepoint_gw_sec/usr/lib

##################################################

PROGRAMS:=automation_relayd

automation_relayd: automation_relayd.c
	$(CC) -o $@ $^ $(CFLAGS) $(LDFLAGS)

all: $(PROGRAMS)

clean:
	rm -f *.o $(PROGRAMS)
