#!/bin/sh

SCRIPTNAME=`basename $0`
BASE_LDIR=~
CMD_TO_RUN=
WPATH=
WDRIVE=

if test "x$WINBLD_BASE_DIR" = x
then 
  BASE_LDIR=$HOME
else
  BASE_LDIR=$WINBLD_BASE_DIR
fi

print_help ()   # Print help
{
  echo "$SCRIPTNAME [options]"
  echo ""
  echo "options:"
  echo "  -w win_path,"
  echo "  --win-path win_path     - cmd dir in Windows notation"
  echo "  -s win_subdir,"
  echo "  --win-subdir win_subdir - subdir to be ignored in Windows notation"
  echo "  -x,"
  echo "  --execute               - command to execute"
  echo "  -h,"
  echo "  --help                  - print this help"
}

until [ -z "$1" ]  # Until all parameters used up . . .
do
  case "$1" in
    -h | --help )
      print_help
      ;;
    -w | --win-path )
      shift
      WPATH="$1"
      ;;
    -x | --execute )
      shift
      CMD_TO_RUN="$1"
      ;;
     -* )
      echo "WARNING: Unknown parameter '$1'"
      shift
      ;;
     * )
      echo "WARNING: Unknown parameter '$1'"
      ;;
  esac
  shift
done

#echo WPATH=$WPATH
#echo CMD_TO_RUN=$CMD_TO_RUN

LPATH=`echo $WPATH | sed -e 's#\\\\#\\/#g' -e "s#^..#$BASE_LDIR#"`
WDRIVE=`echo $WPATH | sed -e "s#^\(..\).*#\1#g"`

#echo LPATH=$LPATH
#echo WPATH=$WPATH
#echo WDRIVE=$WDRIVE

echo "[$LPATH:$CMD_TO_RUN]"
cd $LPATH && ( sh -c "$CMD_TO_RUN" ) 2>&1 | sed -u -e "s#$BASE_LDIR#$WDRIVE#g" -e 's#\/#\\#g' -e "s#\:\([0-9]\+\):#\(\1\) :#"


