/*
 * This file is part of ltrace.
 * Copyright (C) 2012 Andreas Schwab
 * Copyright (C) 2006 Ian Wienand
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 */

	"restart_syscall",                 /* 0 */
	"exit",                            /* 1 */
	"fork",                            /* 2 */
	"read",                            /* 3 */
	"write",                           /* 4 */
	"open",                            /* 5 */
	"close",                           /* 6 */
	"waitpid",                         /* 7 */
	"creat",                           /* 8 */
	"link",                            /* 9 */
	"unlink",                          /* 10 */
	"execve",                          /* 11 */
	"chdir",                           /* 12 */
	"time",                            /* 13 */
	"mknod",                           /* 14 */
	"chmod",                           /* 15 */
	"chown",                           /* 16 */
	"17",                              /* 17 */
	"oldstat",                         /* 18 */
	"lseek",                           /* 19 */
	"getpid",                          /* 20 */
	"mount",                           /* 21 */
	"umount",                          /* 22 */
	"setuid",                          /* 23 */
	"getuid",                          /* 24 */
	"stime",                           /* 25 */
	"ptrace",                          /* 26 */
	"alarm",                           /* 27 */
	"oldfstat",                        /* 28 */
	"pause",                           /* 29 */
	"utime",                           /* 30 */
	"31",                              /* 31 */
	"32",                              /* 32 */
	"access",                          /* 33 */
	"nice",                            /* 34 */
	"35",                              /* 35 */
	"sync",                            /* 36 */
	"kill",                            /* 37 */
	"rename",                          /* 38 */
	"mkdir",                           /* 39 */
	"rmdir",                           /* 40 */
	"dup",                             /* 41 */
	"pipe",                            /* 42 */
	"times",                           /* 43 */
	"44",                              /* 44 */
	"brk",                             /* 45 */
	"setgid",                          /* 46 */
	"getgid",                          /* 47 */
	"signal",                          /* 48 */
	"geteuid",                         /* 49 */
	"getegid",                         /* 50 */
	"acct",                            /* 51 */
	"umount2",                         /* 52 */
	"53",                              /* 53 */
	"ioctl",                           /* 54 */
	"fcntl",                           /* 55 */
	"56",                              /* 56 */
	"setpgid",                         /* 57 */
	"58",                              /* 58 */
	"59",                              /* 59 */
	"umask",                           /* 60 */
	"chroot",                          /* 61 */
	"ustat",                           /* 62 */
	"dup2",                            /* 63 */
	"getppid",                         /* 64 */
	"getpgrp",                         /* 65 */
	"setsid",                          /* 66 */
	"sigaction",                       /* 67 */
	"sgetmask",                        /* 68 */
	"ssetmask",                        /* 69 */
	"setreuid",                        /* 70 */
	"setregid",                        /* 71 */
	"sigsuspend",                      /* 72 */
	"sigpending",                      /* 73 */
	"sethostname",                     /* 74 */
	"setrlimit",                       /* 75 */
	"getrlimit",                       /* 76 */
	"getrusage",                       /* 77 */
	"gettimeofday",                    /* 78 */
	"settimeofday",                    /* 79 */
	"getgroups",                       /* 80 */
	"setgroups",                       /* 81 */
	"select",                          /* 82 */
	"symlink",                         /* 83 */
	"oldlstat",                        /* 84 */
	"readlink",                        /* 85 */
	"uselib",                          /* 86 */
	"swapon",                          /* 87 */
	"reboot",                          /* 88 */
	"readdir",                         /* 89 */
	"mmap",                            /* 90 */
	"munmap",                          /* 91 */
	"truncate",                        /* 92 */
	"ftruncate",                       /* 93 */
	"fchmod",                          /* 94 */
	"fchown",                          /* 95 */
	"getpriority",                     /* 96 */
	"setpriority",                     /* 97 */
	"98",                              /* 98 */
	"statfs",                          /* 99 */
	"fstatfs",                         /* 100 */
	"101",                             /* 101 */
	"socketcall",                      /* 102 */
	"syslog",                          /* 103 */
	"setitimer",                       /* 104 */
	"getitimer",                       /* 105 */
	"stat",                            /* 106 */
	"lstat",                           /* 107 */
	"fstat",                           /* 108 */
	"109",                             /* 109 */
	"110",                             /* 110 */
	"vhangup",                         /* 111 */
	"112",                             /* 112 */
	"113",                             /* 113 */
	"wait4",                           /* 114 */
	"swapoff",                         /* 115 */
	"sysinfo",                         /* 116 */
	"ipc",                             /* 117 */
	"fsync",                           /* 118 */
	"sigreturn",                       /* 119 */
	"clone",                           /* 120 */
	"setdomainname",                   /* 121 */
	"uname",                           /* 122 */
	"cacheflush",                      /* 123 */
	"adjtimex",                        /* 124 */
	"mprotect",                        /* 125 */
	"sigprocmask",                     /* 126 */
	"create_module",                   /* 127 */
	"init_module",                     /* 128 */
	"delete_module",                   /* 129 */
	"get_kernel_syms",                 /* 130 */
	"quotactl",                        /* 131 */
	"getpgid",                         /* 132 */
	"fchdir",                          /* 133 */
	"bdflush",                         /* 134 */
	"sysfs",                           /* 135 */
	"personality",                     /* 136 */
	"137",                             /* 137 */
	"setfsuid",                        /* 138 */
	"setfsgid",                        /* 139 */
	"_llseek",                         /* 140 */
	"getdents",                        /* 141 */
	"_newselect",                      /* 142 */
	"flock",                           /* 143 */
	"msync",                           /* 144 */
	"readv",                           /* 145 */
	"writev",                          /* 146 */
	"getsid",                          /* 147 */
	"fdatasync",                       /* 148 */
	"_sysctl",                         /* 149 */
	"mlock",                           /* 150 */
	"munlock",                         /* 151 */
	"mlockall",                        /* 152 */
	"munlockall",                      /* 153 */
	"sched_setparam",                  /* 154 */
	"sched_getparam",                  /* 155 */
	"sched_setscheduler",              /* 156 */
	"sched_getscheduler",              /* 157 */
	"sched_yield",                     /* 158 */
	"sched_get_priority_max",          /* 159 */
	"sched_get_priority_min",          /* 160 */
	"sched_rr_get_interval",           /* 161 */
	"nanosleep",                       /* 162 */
	"mremap",                          /* 163 */
	"setresuid",                       /* 164 */
	"getresuid",                       /* 165 */
	"getpagesize",                     /* 166 */
	"query_module",                    /* 167 */
	"poll",                            /* 168 */
	"nfsservctl",                      /* 169 */
	"setresgid",                       /* 170 */
	"getresgid",                       /* 171 */
	"prctl",                           /* 172 */
	"rt_sigreturn",                    /* 173 */
	"rt_sigaction",                    /* 174 */
	"rt_sigprocmask",                  /* 175 */
	"rt_sigpending",                   /* 176 */
	"rt_sigtimedwait",                 /* 177 */
	"rt_sigqueueinfo",                 /* 178 */
	"rt_sigsuspend",                   /* 179 */
	"pread64",                         /* 180 */
	"pwrite64",                        /* 181 */
	"lchown",                          /* 182 */
	"getcwd",                          /* 183 */
	"capget",                          /* 184 */
	"capset",                          /* 185 */
	"sigaltstack",                     /* 186 */
	"sendfile",                        /* 187 */
	"getpmsg",                         /* 188 */
	"putpmsg",                         /* 189 */
	"vfork",                           /* 190 */
	"ugetrlimit",                      /* 191 */
	"mmap2",                           /* 192 */
	"truncate64",                      /* 193 */
	"ftruncate64",                     /* 194 */
	"stat64",                          /* 195 */
	"lstat64",                         /* 196 */
	"fstat64",                         /* 197 */
	"chown32",                         /* 198 */
	"getuid32",                        /* 199 */
	"getgid32",                        /* 200 */
	"geteuid32",                       /* 201 */
	"getegid32",                       /* 202 */
	"setreuid32",                      /* 203 */
	"setregid32",                      /* 204 */
	"getgroups32",                     /* 205 */
	"setgroups32",                     /* 206 */
	"fchown32",                        /* 207 */
	"setresuid32",                     /* 208 */
	"getresuid32",                     /* 209 */
	"setresgid32",                     /* 210 */
	"getresgid32",                     /* 211 */
	"lchown32",                        /* 212 */
	"setuid32",                        /* 213 */
	"setgid32",                        /* 214 */
	"setfsuid32",                      /* 215 */
	"setfsgid32",                      /* 216 */
	"pivot_root",                      /* 217 */
	"218",                             /* 218 */
	"219",                             /* 219 */
	"getdents64",                      /* 220 */
	"gettid",                          /* 221 */
	"tkill",                           /* 222 */
	"setxattr",                        /* 223 */
	"lsetxattr",                       /* 224 */
	"fsetxattr",                       /* 225 */
	"getxattr",                        /* 226 */
	"lgetxattr",                       /* 227 */
	"fgetxattr",                       /* 228 */
	"listxattr",                       /* 229 */
	"llistxattr",                      /* 230 */
	"flistxattr",                      /* 231 */
	"removexattr",                     /* 232 */
	"lremovexattr",                    /* 233 */
	"fremovexattr",                    /* 234 */
	"futex",                           /* 235 */
	"sendfile64",                      /* 236 */
	"mincore",                         /* 237 */
	"madvise",                         /* 238 */
	"fcntl64",                         /* 239 */
	"readahead",                       /* 240 */
	"io_setup",                        /* 241 */
	"io_destroy",                      /* 242 */
	"io_getevents",                    /* 243 */
	"io_submit",                       /* 244 */
	"io_cancel",                       /* 245 */
	"fadvise64",                       /* 246 */
	"exit_group",                      /* 247 */
	"lookup_dcookie",                  /* 248 */
	"epoll_create",                    /* 249 */
	"epoll_ctl",                       /* 250 */
	"epoll_wait",                      /* 251 */
	"remap_file_pages",                /* 252 */
	"set_tid_address",                 /* 253 */
	"timer_create",                    /* 254 */
	"timer_settime",                   /* 255 */
	"timer_gettime",                   /* 256 */
	"timer_getoverrun",                /* 257 */
	"timer_delete",                    /* 258 */
	"clock_settime",                   /* 259 */
	"clock_gettime",                   /* 260 */
	"clock_getres",                    /* 261 */
	"clock_nanosleep",                 /* 262 */
	"statfs64",                        /* 263 */
	"fstatfs64",                       /* 264 */
	"tgkill",                          /* 265 */
	"utimes",                          /* 266 */
	"fadvise64_64",                    /* 267 */
	"mbind",                           /* 268 */
	"get_mempolicy",                   /* 269 */
	"set_mempolicy",                   /* 270 */
	"mq_open",                         /* 271 */
	"mq_unlink",                       /* 272 */
	"mq_timedsend",                    /* 273 */
	"mq_timedreceive",                 /* 274 */
	"mq_notify",                       /* 275 */
	"mq_getsetattr",                   /* 276 */
	"waitid",                          /* 277 */
	"278",                             /* 278 */
	"add_key",                         /* 279 */
	"request_key",                     /* 280 */
	"keyctl",                          /* 281 */
	"ioprio_set",                      /* 282 */
	"ioprio_get",                      /* 283 */
	"inotify_init",                    /* 284 */
	"inotify_add_watch",               /* 285 */
	"inotify_rm_watch",                /* 286 */
	"migrate_pages",                   /* 287 */
	"openat",                          /* 288 */
	"mkdirat",                         /* 289 */
	"mknodat",                         /* 290 */
	"fchownat",                        /* 291 */
	"futimesat",                       /* 292 */
	"fstatat64",                       /* 293 */
	"unlinkat",                        /* 294 */
	"renameat",                        /* 295 */
	"linkat",                          /* 296 */
	"symlinkat",                       /* 297 */
	"readlinkat",                      /* 298 */
	"fchmodat",                        /* 299 */
	"faccessat",                       /* 300 */
	"pselect6",                        /* 301 */
	"ppoll",                           /* 302 */
	"unshare",                         /* 303 */
	"set_robust_list",                 /* 304 */
	"get_robust_list",                 /* 305 */
	"splice",                          /* 306 */
	"sync_file_range",                 /* 307 */
	"tee",                             /* 308 */
	"vmsplice",                        /* 309 */
	"move_pages",                      /* 310 */
	"sched_setaffinity",               /* 311 */
	"sched_getaffinity",               /* 312 */
	"kexec_load",                      /* 313 */
	"getcpu",                          /* 314 */
	"epoll_pwait",                     /* 315 */
	"utimensat",                       /* 316 */
	"signalfd",                        /* 317 */
	"timerfd_create",                  /* 318 */
	"eventfd",                         /* 319 */
	"fallocate",                       /* 320 */
	"timerfd_settime",                 /* 321 */
	"timerfd_gettime",                 /* 322 */
	"signalfd4",                       /* 323 */
	"eventfd2",                        /* 324 */
	"epoll_create1",                   /* 325 */
	"dup3",                            /* 326 */
	"pipe2",                           /* 327 */
	"inotify_init1",                   /* 328 */
	"preadv",                          /* 329 */
	"pwritev",                         /* 330 */
	"rt_tgsigqueueinfo",               /* 331 */
	"perf_event_open",                 /* 332 */
	"get_thread_area",                 /* 333 */
	"set_thread_area",                 /* 334 */
	"atomic_cmpxchg_32",               /* 335 */
	"atomic_barrier",                  /* 336 */
	"fanotify_init",                   /* 337 */
	"fanotify_mark",                   /* 338 */
	"prlimit64",                       /* 339 */
	"name_to_handle_at",               /* 340 */
	"open_by_handle_at",               /* 341 */
	"clock_adjtime",                   /* 342 */
	"syncfs",                          /* 343 */
	"setns",                           /* 344 */
	"process_vm_readv",                /* 345 */
	"process_vm_writev",               /* 346 */
